"""Generate statically typed Python classes from a SysML model.

Usage::

    python -m pysysml.generate model.sysml -o model_types.py

The generated module contains one class per SysML definition, deriving from
:class:`pysysml.typed.TypedObject`, with one property per feature. Output is a
runtime ``.py`` (no separate stub): the properties both carry the static type and
perform the runtime delegation to the Tier 1 instance, so a single artifact stays
in step with itself. Emission is deterministic — symbols are ordered by
fully-qualified name and nothing environment-dependent is written — so the output
can be committed as a golden file.
"""

import argparse
import keyword
import sys
from dataclasses import dataclass, field
from typing import Dict, Iterable, List, Optional, Sequence, Tuple

from pysysml.typefacts import Multiplicity, Specialization, SymbolFacts, TypeFacts

GENERATED_HEADER = "# Generated by pysysml.generate. Do not edit."

# Definition kinds get a class; these usage kinds become properties on the
# enclosing class. Behavioral and connector usages (action, state, calc,
# constraint, requirement, connection, flow, interface, allocation, case) are
# not instance slots and are skipped — see python/README.md.
FEATURE_KINDS = frozenset(
    {
        "attributeusage",
        "partusage",
        "itemusage",
        "occurrenceusage",
        "individualusage",
        "portusage",
        "enumusage",
    }
)

PRIMITIVE_TYPES = {
    "Boolean": "bool",
    "String": "str",
    "Natural": "int",
    "Integer": "int",
    "Rational": "float",
    "Real": "float",
}

# Library scalars with no sound Python counterpart, mapped to `object`.
UNMAPPED_PRIMITIVES = frozenset({"Complex", "Number"})


def is_definition_kind(kind: str) -> bool:
    """Whether a symbol kind declares a type, e.g. ``partDef`` or ``metaclass``."""
    lowered = kind.lower()
    return lowered.endswith("def") or lowered == "metaclass"


def is_feature_kind(kind: str) -> bool:
    """Whether a symbol kind is a usage exposed as an instance slot."""
    return kind.lower() in FEATURE_KINDS


@dataclass(frozen=True)
class Feature:
    """One SysML feature to emit as a property."""

    facts: SymbolFacts

    @property
    def name(self) -> str:
        return self.facts.name


@dataclass(frozen=True)
class Definition:
    """One SysML definition to emit as a class."""

    facts: SymbolFacts
    features: Tuple[Feature, ...] = field(default_factory=tuple)

    @property
    def id(self) -> str:
        return self.facts.id

    @property
    def name(self) -> str:
        return self.facts.name

    @property
    def base_ids(self) -> Tuple[str, ...]:
        """FQNs of the definitions this one specializes, in declaration order."""
        return tuple(
            spec.target_id
            for spec in self.facts.specializations
            if spec.kind == "specializes" and spec.target_id
        )


@dataclass(frozen=True)
class PythonType:
    """A rendered Python annotation plus the reason it was chosen, when notable."""

    annotation: str
    decoder: str
    comment: str = ""


def collect_definitions(root) -> List[Definition]:
    """Walk a :class:`~pysysml.symbol.Symbol` tree and collect its definitions.

    Definitions are returned sorted by FQN so that generation is deterministic.
    """
    definitions: List[Definition] = []
    _collect(root, definitions)
    definitions.sort(key=lambda definition: definition.id)
    return definitions


def _collect(symbol, out: List[Definition]) -> None:
    children = symbol.children()
    if is_definition_kind(symbol.kind):
        features = tuple(
            Feature(child.facts())
            for child in sorted(children, key=lambda child: child.id)
            if is_feature_kind(child.kind)
        )
        out.append(Definition(symbol.facts(), features))
    for child in children:
        _collect(child, out)


def class_names(definitions: Sequence[Definition]) -> Dict[str, str]:
    """Map definition FQN → Python class name.

    A simple name declared by more than one definition is qualified with its
    owning path so that every generated class name is unique and stable.
    """
    by_name: Dict[str, List[Definition]] = {}
    for definition in definitions:
        by_name.setdefault(_identifier(definition.name), []).append(definition)

    names: Dict[str, str] = {}
    for simple, group in by_name.items():
        if len(group) == 1:
            names[group[0].id] = simple
            continue
        for definition in group:
            names[definition.id] = "_".join(
                _identifier(part) for part in definition.id.split("::")
            )
    return names


def _identifier(name: str) -> str:
    """Turn a SysML name into a Python identifier."""
    cleaned = "".join(char if char.isalnum() or char == "_" else "_" for char in name)
    if not cleaned or cleaned[0].isdigit():
        cleaned = "_" + cleaned
    if keyword.iskeyword(cleaned):
        cleaned += "_"
    return cleaned


def element_type(type_facts: Optional[TypeFacts], names: Dict[str, str]) -> PythonType:
    """Map the type of a single value to a Python annotation and decoder."""
    if type_facts is None:
        return PythonType("object", "_t.as_object", "untyped feature")

    if type_facts.quantity:
        unit = type_facts.unit or "unknown unit"
        return PythonType(
            "object",
            "_t.as_object",
            f"quantity in [{unit}]; the wire format carries no magnitude-and-unit value",
        )

    # A definition reducing to a library scalar holds that scalar, not an
    # instance, even when it has a generated class of its own.
    primitive = type_facts.primitive
    if primitive in PRIMITIVE_TYPES:
        python = PRIMITIVE_TYPES[primitive]
        return PythonType(python, f"_t.as_{python}")

    if type_facts.resolved_id and type_facts.resolved_id in names:
        generated = names[type_facts.resolved_id]
        return PythonType(generated, f"_t.as_typed({generated})")

    if primitive in UNMAPPED_PRIMITIVES:
        return PythonType("object", "_t.as_object", f"SysML {primitive} has no Python counterpart")

    if type_facts.resolved_id:
        return PythonType(
            "object", "_t.as_object", f"SysML type {type_facts.resolved_id} has no generated class"
        )

    if type_facts.declared:
        return PythonType("object", "_t.as_object", f"unresolved SysML type {type_facts.declared}")

    return PythonType("object", "_t.as_object", "untyped feature")


def feature_type(feature: Feature, names: Dict[str, str]) -> PythonType:
    """Map a feature to its Python annotation, decoder and accessor, honoring multiplicity."""
    element = element_type(feature.facts.type, names)
    multiplicity = feature.facts.multiplicity or Multiplicity()

    if multiplicity.is_collection:
        return PythonType(f"list[{element.annotation}]", element.decoder, element.comment)
    if multiplicity.is_optional:
        return PythonType(f"{element.annotation} | None", element.decoder, element.comment)
    return element


def _accessor(feature: Feature) -> str:
    multiplicity = feature.facts.multiplicity or Multiplicity()
    if multiplicity.is_collection:
        return "_t.list_slot"
    if multiplicity.is_optional:
        return "_t.optional_slot"
    return "_t.slot"


def render_module(definitions: Sequence[Definition]) -> str:
    """Render a complete, importable Python module for ``definitions``."""
    names = class_names(definitions)
    lines: List[str] = [
        GENERATED_HEADER,
        '"""Typed views over SysML definitions, generated from a parsed model."""',
        "",
        "from __future__ import annotations",
        "",
        "from pysysml import typed as _t",
    ]
    if not definitions:
        lines.append("")
        return "\n".join(lines)

    for definition in _in_dependency_order(definitions):
        lines.extend(("", ""))
        lines.extend(_render_class(definition, names))
    lines.append("")
    return "\n".join(lines)


def _in_dependency_order(definitions: Sequence[Definition]) -> List[Definition]:
    """Order definitions so a base class is emitted before its subclasses.

    Ties and cycles keep FQN order, so emission stays deterministic.
    """
    by_id = {definition.id: definition for definition in definitions}
    ordered: List[Definition] = []
    emitted: set = set()
    visiting: set = set()

    def visit(definition: Definition) -> None:
        if definition.id in emitted or definition.id in visiting:
            return
        visiting.add(definition.id)
        for base_id in definition.base_ids:
            base = by_id.get(base_id)
            if base is not None:
                visit(base)
        visiting.discard(definition.id)
        emitted.add(definition.id)
        ordered.append(definition)

    for definition in definitions:
        visit(definition)
    return ordered


def _render_class(definition: Definition, names: Dict[str, str]) -> List[str]:
    bases = [names[base_id] for base_id in definition.base_ids if base_id in names]
    unmapped = [base_id for base_id in definition.base_ids if base_id not in names]
    header = f"class {names[definition.id]}({', '.join(bases) if bases else '_t.TypedObject'}):"

    lines = [header, f'    """{definition.facts.kind} {definition.id}."""', ""]
    for base_id in unmapped:
        lines.insert(2, f"    # specializes {base_id}, which has no generated class")
    lines.append(f'    sysml_id = "{definition.id}"')

    for feature in definition.features:
        lines.append("")
        lines.extend(_render_property(feature, names))
    return lines


def _render_property(feature: Feature, names: Dict[str, str]) -> List[str]:
    python_type = feature_type(feature, names)
    identifier = _identifier(feature.name)
    lines = ["    @property", f"    def {identifier}(self) -> {python_type.annotation}:"]
    doc = f"{feature.facts.kind} {feature.facts.id}."
    if python_type.comment:
        doc += f" Mapped to {python_type.annotation}: {python_type.comment}."
    lines.append(f'        """{doc}"""')
    lines.append(
        f'        return {_accessor(feature)}(self, "{feature.name}", {python_type.decoder})'
    )
    return lines


def generate_source(model) -> str:
    """Render the typed module for a loaded :class:`~pysysml.model.Model`."""
    return render_module(collect_definitions(model.root))


def main(argv: Optional[Iterable[str]] = None) -> int:
    """Entry point for ``python -m pysysml.generate``."""
    parser = argparse.ArgumentParser(
        prog="python -m pysysml.generate",
        description="Generate typed Python classes from a SysML model.",
    )
    parser.add_argument("source", help="path to a .sysml file")
    parser.add_argument("-o", "--output", help="output .py path (default: stdout)")
    parser.add_argument("--host", default="localhost", help="sysml-grpc host")
    parser.add_argument("--port", type=int, default=50051, help="sysml-grpc port")
    args = parser.parse_args(list(argv) if argv is not None else None)

    import pysysml

    model = pysysml.load(args.source, host=args.host, port=args.port)
    errors = [diag for diag in model.diagnostics if diag.severity == "error"]
    if errors:
        for diag in errors:
            print(f"error: {diag.message}", file=sys.stderr)
        return 1

    source = generate_source(model)
    if args.output:
        with open(args.output, "w", encoding="utf-8") as handle:
            handle.write(source)
    else:
        sys.stdout.write(source)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
