# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import sysml_pb2 as sysml__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in sysml_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SysMLServiceStub:
    """SysMLService provides programmatic access to Systemica's parser and runtime
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetServerInfo = channel.unary_unary(
                '/sysml.SysMLService/GetServerInfo',
                request_serializer=sysml__pb2.ServerInfoRequest.SerializeToString,
                response_deserializer=sysml__pb2.ServerInfoResponse.FromString,
                _registered_method=True)
        self.ParseFile = channel.unary_unary(
                '/sysml.SysMLService/ParseFile',
                request_serializer=sysml__pb2.ParseFileRequest.SerializeToString,
                response_deserializer=sysml__pb2.ParseFileResponse.FromString,
                _registered_method=True)
        self.GetSymbol = channel.unary_unary(
                '/sysml.SysMLService/GetSymbol',
                request_serializer=sysml__pb2.GetSymbolRequest.SerializeToString,
                response_deserializer=sysml__pb2.SymbolResponse.FromString,
                _registered_method=True)
        self.GetDiagnostics = channel.unary_unary(
                '/sysml.SysMLService/GetDiagnostics',
                request_serializer=sysml__pb2.DiagnosticsRequest.SerializeToString,
                response_deserializer=sysml__pb2.DiagnosticsResponse.FromString,
                _registered_method=True)
        self.Evaluate = channel.unary_unary(
                '/sysml.SysMLService/Evaluate',
                request_serializer=sysml__pb2.EvaluateRequest.SerializeToString,
                response_deserializer=sysml__pb2.EvaluateResponse.FromString,
                _registered_method=True)
        self.Instantiate = channel.unary_unary(
                '/sysml.SysMLService/Instantiate',
                request_serializer=sysml__pb2.InstantiateRequest.SerializeToString,
                response_deserializer=sysml__pb2.InstantiateResponse.FromString,
                _registered_method=True)
        self.ExecuteAction = channel.unary_unary(
                '/sysml.SysMLService/ExecuteAction',
                request_serializer=sysml__pb2.ExecuteActionRequest.SerializeToString,
                response_deserializer=sysml__pb2.ExecuteActionResponse.FromString,
                _registered_method=True)
        self.ExecuteState = channel.unary_unary(
                '/sysml.SysMLService/ExecuteState',
                request_serializer=sysml__pb2.ExecuteStateRequest.SerializeToString,
                response_deserializer=sysml__pb2.ExecuteStateResponse.FromString,
                _registered_method=True)


class SysMLServiceServicer:
    """SysMLService provides programmatic access to Systemica's parser and runtime
    """

    def GetServerInfo(self, request, context):
        """Report what this build of the service can do, so a client can require a
        capability instead of guessing from a version string. A service that
        predates this RPC answers UNIMPLEMENTED, which is itself the answer.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ParseFile(self, request, context):
        """Parse a SysML file and return model hash for subsequent queries
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSymbol(self, request, context):
        """Get symbol information by qualified name
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDiagnostics(self, request, context):
        """Get all diagnostics for a parsed model
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Evaluate(self, request, context):
        """Runtime operations (Phase 4)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Instantiate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteAction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SysMLServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetServerInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetServerInfo,
                    request_deserializer=sysml__pb2.ServerInfoRequest.FromString,
                    response_serializer=sysml__pb2.ServerInfoResponse.SerializeToString,
            ),
            'ParseFile': grpc.unary_unary_rpc_method_handler(
                    servicer.ParseFile,
                    request_deserializer=sysml__pb2.ParseFileRequest.FromString,
                    response_serializer=sysml__pb2.ParseFileResponse.SerializeToString,
            ),
            'GetSymbol': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSymbol,
                    request_deserializer=sysml__pb2.GetSymbolRequest.FromString,
                    response_serializer=sysml__pb2.SymbolResponse.SerializeToString,
            ),
            'GetDiagnostics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDiagnostics,
                    request_deserializer=sysml__pb2.DiagnosticsRequest.FromString,
                    response_serializer=sysml__pb2.DiagnosticsResponse.SerializeToString,
            ),
            'Evaluate': grpc.unary_unary_rpc_method_handler(
                    servicer.Evaluate,
                    request_deserializer=sysml__pb2.EvaluateRequest.FromString,
                    response_serializer=sysml__pb2.EvaluateResponse.SerializeToString,
            ),
            'Instantiate': grpc.unary_unary_rpc_method_handler(
                    servicer.Instantiate,
                    request_deserializer=sysml__pb2.InstantiateRequest.FromString,
                    response_serializer=sysml__pb2.InstantiateResponse.SerializeToString,
            ),
            'ExecuteAction': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteAction,
                    request_deserializer=sysml__pb2.ExecuteActionRequest.FromString,
                    response_serializer=sysml__pb2.ExecuteActionResponse.SerializeToString,
            ),
            'ExecuteState': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteState,
                    request_deserializer=sysml__pb2.ExecuteStateRequest.FromString,
                    response_serializer=sysml__pb2.ExecuteStateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sysml.SysMLService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sysml.SysMLService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SysMLService:
    """SysMLService provides programmatic access to Systemica's parser and runtime
    """

    @staticmethod
    def GetServerInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sysml.SysMLService/GetServerInfo',
            sysml__pb2.ServerInfoRequest.SerializeToString,
            sysml__pb2.ServerInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ParseFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sysml.SysMLService/ParseFile',
            sysml__pb2.ParseFileRequest.SerializeToString,
            sysml__pb2.ParseFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSymbol(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sysml.SysMLService/GetSymbol',
            sysml__pb2.GetSymbolRequest.SerializeToString,
            sysml__pb2.SymbolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDiagnostics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sysml.SysMLService/GetDiagnostics',
            sysml__pb2.DiagnosticsRequest.SerializeToString,
            sysml__pb2.DiagnosticsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Evaluate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sysml.SysMLService/Evaluate',
            sysml__pb2.EvaluateRequest.SerializeToString,
            sysml__pb2.EvaluateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Instantiate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sysml.SysMLService/Instantiate',
            sysml__pb2.InstantiateRequest.SerializeToString,
            sysml__pb2.InstantiateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sysml.SysMLService/ExecuteAction',
            sysml__pb2.ExecuteActionRequest.SerializeToString,
            sysml__pb2.ExecuteActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sysml.SysMLService/ExecuteState',
            sysml__pb2.ExecuteStateRequest.SerializeToString,
            sysml__pb2.ExecuteStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
