// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: sysml.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ParseFileRequest specifies the source to parse
type ParseFileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Source:
	//
	//	*ParseFileRequest_FilePath
	//	*ParseFileRequest_Content
	Source        isParseFileRequest_Source `protobuf_oneof:"source"`
	ContentHash   string                    `protobuf:"bytes,3,opt,name=content_hash,json=contentHash,proto3" json:"content_hash,omitempty"` // sha256 for cache lookup
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseFileRequest) Reset() {
	*x = ParseFileRequest{}
	mi := &file_sysml_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseFileRequest) ProtoMessage() {}

func (x *ParseFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sysml_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseFileRequest.ProtoReflect.Descriptor instead.
func (*ParseFileRequest) Descriptor() ([]byte, []int) {
	return file_sysml_proto_rawDescGZIP(), []int{0}
}

func (x *ParseFileRequest) GetSource() isParseFileRequest_Source {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *ParseFileRequest) GetFilePath() string {
	if x != nil {
		if x, ok := x.Source.(*ParseFileRequest_FilePath); ok {
			return x.FilePath
		}
	}
	return ""
}

func (x *ParseFileRequest) GetContent() string {
	if x != nil {
		if x, ok := x.Source.(*ParseFileRequest_Content); ok {
			return x.Content
		}
	}
	return ""
}

func (x *ParseFileRequest) GetContentHash() string {
	if x != nil {
		return x.ContentHash
	}
	return ""
}

type isParseFileRequest_Source interface {
	isParseFileRequest_Source()
}

type ParseFileRequest_FilePath struct {
	FilePath string `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3,oneof"`
}

type ParseFileRequest_Content struct {
	Content string `protobuf:"bytes,2,opt,name=content,proto3,oneof"`
}

func (*ParseFileRequest_FilePath) isParseFileRequest_Source() {}

func (*ParseFileRequest_Content) isParseFileRequest_Source() {}

// ParseFileResponse contains parsed model info
type ParseFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelHash     string                 `protobuf:"bytes,1,opt,name=model_hash,json=modelHash,proto3" json:"model_hash,omitempty"` // Cache key for subsequent requests
	Root          *SymbolInfo            `protobuf:"bytes,2,opt,name=root,proto3" json:"root,omitempty"`                            // Root namespace
	Diagnostics   []*Diagnostic          `protobuf:"bytes,3,rep,name=diagnostics,proto3" json:"diagnostics,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"` // Critical failure message if any
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseFileResponse) Reset() {
	*x = ParseFileResponse{}
	mi := &file_sysml_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseFileResponse) ProtoMessage() {}

func (x *ParseFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sysml_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseFileResponse.ProtoReflect.Descriptor instead.
func (*ParseFileResponse) Descriptor() ([]byte, []int) {
	return file_sysml_proto_rawDescGZIP(), []int{1}
}

func (x *ParseFileResponse) GetModelHash() string {
	if x != nil {
		return x.ModelHash
	}
	return ""
}

func (x *ParseFileResponse) GetRoot() *SymbolInfo {
	if x != nil {
		return x.Root
	}
	return nil
}

func (x *ParseFileResponse) GetDiagnostics() []*Diagnostic {
	if x != nil {
		return x.Diagnostics
	}
	return nil
}

func (x *ParseFileResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// GetSymbolRequest queries for a specific symbol
type GetSymbolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelHash     string                 `protobuf:"bytes,1,opt,name=model_hash,json=modelHash,proto3" json:"model_hash,omitempty"`
	SymbolId      string                 `protobuf:"bytes,2,opt,name=symbol_id,json=symbolId,proto3" json:"symbol_id,omitempty"` // Fully qualified name
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSymbolRequest) Reset() {
	*x = GetSymbolRequest{}
	mi := &file_sysml_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSymbolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSymbolRequest) ProtoMessage() {}

func (x *GetSymbolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sysml_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSymbolRequest.ProtoReflect.Descriptor instead.
func (*GetSymbolRequest) Descriptor() ([]byte, []int) {
	return file_sysml_proto_rawDescGZIP(), []int{2}
}

func (x *GetSymbolRequest) GetModelHash() string {
	if x != nil {
		return x.ModelHash
	}
	return ""
}

func (x *GetSymbolRequest) GetSymbolId() string {
	if x != nil {
		return x.SymbolId
	}
	return ""
}

// SymbolResponse contains symbol information
type SymbolResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        *SymbolInfo            `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SymbolResponse) Reset() {
	*x = SymbolResponse{}
	mi := &file_sysml_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SymbolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SymbolResponse) ProtoMessage() {}

func (x *SymbolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sysml_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SymbolResponse.ProtoReflect.Descriptor instead.
func (*SymbolResponse) Descriptor() ([]byte, []int) {
	return file_sysml_proto_rawDescGZIP(), []int{3}
}

func (x *SymbolResponse) GetSymbol() *SymbolInfo {
	if x != nil {
		return x.Symbol
	}
	return nil
}

func (x *SymbolResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// DiagnosticsRequest gets all diagnostics for a model
type DiagnosticsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelHash     string                 `protobuf:"bytes,1,opt,name=model_hash,json=modelHash,proto3" json:"model_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiagnosticsRequest) Reset() {
	*x = DiagnosticsRequest{}
	mi := &file_sysml_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiagnosticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiagnosticsRequest) ProtoMessage() {}

func (x *DiagnosticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sysml_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiagnosticsRequest.ProtoReflect.Descriptor instead.
func (*DiagnosticsRequest) Descriptor() ([]byte, []int) {
	return file_sysml_proto_rawDescGZIP(), []int{4}
}

func (x *DiagnosticsRequest) GetModelHash() string {
	if x != nil {
		return x.ModelHash
	}
	return ""
}

// DiagnosticsResponse contains diagnostic list
type DiagnosticsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Diagnostics   []*Diagnostic          `protobuf:"bytes,1,rep,name=diagnostics,proto3" json:"diagnostics,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiagnosticsResponse) Reset() {
	*x = DiagnosticsResponse{}
	mi := &file_sysml_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiagnosticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiagnosticsResponse) ProtoMessage() {}

func (x *DiagnosticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sysml_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiagnosticsResponse.ProtoReflect.Descriptor instead.
func (*DiagnosticsResponse) Descriptor() ([]byte, []int) {
	return file_sysml_proto_rawDescGZIP(), []int{5}
}

func (x *DiagnosticsResponse) GetDiagnostics() []*Diagnostic {
	if x != nil {
		return x.Diagnostics
	}
	return nil
}

func (x *DiagnosticsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// SymbolInfo represents any SysML element
type SymbolInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // Unique identifier (fully qualified name)
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Kind          string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`                                                                                   // "PartDefinition", "AttributeUsage", etc
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // multiplicity, type, etc
	ChildIds      []string               `protobuf:"bytes,5,rep,name=child_ids,json=childIds,proto3" json:"child_ids,omitempty"`                                                           // References to children
	Attributes    []*AttributeInfo       `protobuf:"bytes,6,rep,name=attributes,proto3" json:"attributes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SymbolInfo) Reset() {
	*x = SymbolInfo{}
	mi := &file_sysml_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SymbolInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SymbolInfo) ProtoMessage() {}

func (x *SymbolInfo) ProtoReflect() protoreflect.Message {
	mi := &file_sysml_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SymbolInfo.ProtoReflect.Descriptor instead.
func (*SymbolInfo) Descriptor() ([]byte, []int) {
	return file_sysml_proto_rawDescGZIP(), []int{6}
}

func (x *SymbolInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SymbolInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SymbolInfo) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *SymbolInfo) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *SymbolInfo) GetChildIds() []string {
	if x != nil {
		return x.ChildIds
	}
	return nil
}

func (x *SymbolInfo) GetAttributes() []*AttributeInfo {
	if x != nil {
		return x.Attributes
	}
	return nil
}

// AttributeInfo represents an attribute with its value
type AttributeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Value         *Value                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Unit          string                 `protobuf:"bytes,4,opt,name=unit,proto3" json:"unit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttributeInfo) Reset() {
	*x = AttributeInfo{}
	mi := &file_sysml_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttributeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributeInfo) ProtoMessage() {}

func (x *AttributeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_sysml_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributeInfo.ProtoReflect.Descriptor instead.
func (*AttributeInfo) Descriptor() ([]byte, []int) {
	return file_sysml_proto_rawDescGZIP(), []int{7}
}

func (x *AttributeInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AttributeInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AttributeInfo) GetValue() *Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *AttributeInfo) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

// Value represents a literal value
type Value struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*Value_Number
	//	*Value_Text
	//	*Value_Boolean
	//	*Value_Integer
	Value         isValue_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_sysml_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_sysml_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_sysml_proto_rawDescGZIP(), []int{8}
}

func (x *Value) GetValue() isValue_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Value) GetNumber() float64 {
	if x != nil {
		if x, ok := x.Value.(*Value_Number); ok {
			return x.Number
		}
	}
	return 0
}

func (x *Value) GetText() string {
	if x != nil {
		if x, ok := x.Value.(*Value_Text); ok {
			return x.Text
		}
	}
	return ""
}

func (x *Value) GetBoolean() bool {
	if x != nil {
		if x, ok := x.Value.(*Value_Boolean); ok {
			return x.Boolean
		}
	}
	return false
}

func (x *Value) GetInteger() int64 {
	if x != nil {
		if x, ok := x.Value.(*Value_Integer); ok {
			return x.Integer
		}
	}
	return 0
}

type isValue_Value interface {
	isValue_Value()
}

type Value_Number struct {
	Number float64 `protobuf:"fixed64,1,opt,name=number,proto3,oneof"`
}

type Value_Text struct {
	Text string `protobuf:"bytes,2,opt,name=text,proto3,oneof"`
}

type Value_Boolean struct {
	Boolean bool `protobuf:"varint,3,opt,name=boolean,proto3,oneof"`
}

type Value_Integer struct {
	Integer int64 `protobuf:"varint,4,opt,name=integer,proto3,oneof"`
}

func (*Value_Number) isValue_Value() {}

func (*Value_Text) isValue_Value() {}

func (*Value_Boolean) isValue_Value() {}

func (*Value_Integer) isValue_Value() {}

// Diagnostic represents a parse/semantic error or warning
type Diagnostic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Severity      string                 `protobuf:"bytes,1,opt,name=severity,proto3" json:"severity,omitempty"` // "error", "warning", "info"
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Span          *Span                  `protobuf:"bytes,3,opt,name=span,proto3" json:"span,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Diagnostic) Reset() {
	*x = Diagnostic{}
	mi := &file_sysml_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Diagnostic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Diagnostic) ProtoMessage() {}

func (x *Diagnostic) ProtoReflect() protoreflect.Message {
	mi := &file_sysml_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Diagnostic.ProtoReflect.Descriptor instead.
func (*Diagnostic) Descriptor() ([]byte, []int) {
	return file_sysml_proto_rawDescGZIP(), []int{9}
}

func (x *Diagnostic) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *Diagnostic) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Diagnostic) GetSpan() *Span {
	if x != nil {
		return x.Span
	}
	return nil
}

// Span represents a source location
type Span struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          string                 `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	StartLine     int32                  `protobuf:"varint,2,opt,name=start_line,json=startLine,proto3" json:"start_line,omitempty"`
	StartCol      int32                  `protobuf:"varint,3,opt,name=start_col,json=startCol,proto3" json:"start_col,omitempty"`
	EndLine       int32                  `protobuf:"varint,4,opt,name=end_line,json=endLine,proto3" json:"end_line,omitempty"`
	EndCol        int32                  `protobuf:"varint,5,opt,name=end_col,json=endCol,proto3" json:"end_col,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Span) Reset() {
	*x = Span{}
	mi := &file_sysml_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Span) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Span) ProtoMessage() {}

func (x *Span) ProtoReflect() protoreflect.Message {
	mi := &file_sysml_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Span.ProtoReflect.Descriptor instead.
func (*Span) Descriptor() ([]byte, []int) {
	return file_sysml_proto_rawDescGZIP(), []int{10}
}

func (x *Span) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *Span) GetStartLine() int32 {
	if x != nil {
		return x.StartLine
	}
	return 0
}

func (x *Span) GetStartCol() int32 {
	if x != nil {
		return x.StartCol
	}
	return 0
}

func (x *Span) GetEndLine() int32 {
	if x != nil {
		return x.EndLine
	}
	return 0
}

func (x *Span) GetEndCol() int32 {
	if x != nil {
		return x.EndCol
	}
	return 0
}

var File_sysml_proto protoreflect.FileDescriptor

const file_sysml_proto_rawDesc = "" +
	"\n" +
	"\vsysml.proto\x12\x05sysml\"z\n" +
	"\x10ParseFileRequest\x12\x1d\n" +
	"\tfile_path\x18\x01 \x01(\tH\x00R\bfilePath\x12\x1a\n" +
	"\acontent\x18\x02 \x01(\tH\x00R\acontent\x12!\n" +
	"\fcontent_hash\x18\x03 \x01(\tR\vcontentHashB\b\n" +
	"\x06source\"\xa4\x01\n" +
	"\x11ParseFileResponse\x12\x1d\n" +
	"\n" +
	"model_hash\x18\x01 \x01(\tR\tmodelHash\x12%\n" +
	"\x04root\x18\x02 \x01(\v2\x11.sysml.SymbolInfoR\x04root\x123\n" +
	"\vdiagnostics\x18\x03 \x03(\v2\x11.sysml.DiagnosticR\vdiagnostics\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"N\n" +
	"\x10GetSymbolRequest\x12\x1d\n" +
	"\n" +
	"model_hash\x18\x01 \x01(\tR\tmodelHash\x12\x1b\n" +
	"\tsymbol_id\x18\x02 \x01(\tR\bsymbolId\"Q\n" +
	"\x0eSymbolResponse\x12)\n" +
	"\x06symbol\x18\x01 \x01(\v2\x11.sysml.SymbolInfoR\x06symbol\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"3\n" +
	"\x12DiagnosticsRequest\x12\x1d\n" +
	"\n" +
	"model_hash\x18\x01 \x01(\tR\tmodelHash\"`\n" +
	"\x13DiagnosticsResponse\x123\n" +
	"\vdiagnostics\x18\x01 \x03(\v2\x11.sysml.DiagnosticR\vdiagnostics\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x91\x02\n" +
	"\n" +
	"SymbolInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12;\n" +
	"\bmetadata\x18\x04 \x03(\v2\x1f.sysml.SymbolInfo.MetadataEntryR\bmetadata\x12\x1b\n" +
	"\tchild_ids\x18\x05 \x03(\tR\bchildIds\x124\n" +
	"\n" +
	"attributes\x18\x06 \x03(\v2\x14.sysml.AttributeInfoR\n" +
	"attributes\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"o\n" +
	"\rAttributeInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\"\n" +
	"\x05value\x18\x03 \x01(\v2\f.sysml.ValueR\x05value\x12\x12\n" +
	"\x04unit\x18\x04 \x01(\tR\x04unit\"x\n" +
	"\x05Value\x12\x18\n" +
	"\x06number\x18\x01 \x01(\x01H\x00R\x06number\x12\x14\n" +
	"\x04text\x18\x02 \x01(\tH\x00R\x04text\x12\x1a\n" +
	"\aboolean\x18\x03 \x01(\bH\x00R\aboolean\x12\x1a\n" +
	"\ainteger\x18\x04 \x01(\x03H\x00R\aintegerB\a\n" +
	"\x05value\"c\n" +
	"\n" +
	"Diagnostic\x12\x1a\n" +
	"\bseverity\x18\x01 \x01(\tR\bseverity\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\x04span\x18\x03 \x01(\v2\v.sysml.SpanR\x04span\"\x8a\x01\n" +
	"\x04Span\x12\x12\n" +
	"\x04file\x18\x01 \x01(\tR\x04file\x12\x1d\n" +
	"\n" +
	"start_line\x18\x02 \x01(\x05R\tstartLine\x12\x1b\n" +
	"\tstart_col\x18\x03 \x01(\x05R\bstartCol\x12\x19\n" +
	"\bend_line\x18\x04 \x01(\x05R\aendLine\x12\x17\n" +
	"\aend_col\x18\x05 \x01(\x05R\x06endCol2\xd4\x01\n" +
	"\fSysMLService\x12>\n" +
	"\tParseFile\x12\x17.sysml.ParseFileRequest\x1a\x18.sysml.ParseFileResponse\x12;\n" +
	"\tGetSymbol\x12\x17.sysml.GetSymbolRequest\x1a\x15.sysml.SymbolResponse\x12G\n" +
	"\x0eGetDiagnostics\x12\x19.sysml.DiagnosticsRequest\x1a\x1a.sysml.DiagnosticsResponseB*Z(github.com/Open-MBEE/Systemica/api/protob\x06proto3"

var (
	file_sysml_proto_rawDescOnce sync.Once
	file_sysml_proto_rawDescData []byte
)

func file_sysml_proto_rawDescGZIP() []byte {
	file_sysml_proto_rawDescOnce.Do(func() {
		file_sysml_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sysml_proto_rawDesc), len(file_sysml_proto_rawDesc)))
	})
	return file_sysml_proto_rawDescData
}

var file_sysml_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_sysml_proto_goTypes = []any{
	(*ParseFileRequest)(nil),    // 0: sysml.ParseFileRequest
	(*ParseFileResponse)(nil),   // 1: sysml.ParseFileResponse
	(*GetSymbolRequest)(nil),    // 2: sysml.GetSymbolRequest
	(*SymbolResponse)(nil),      // 3: sysml.SymbolResponse
	(*DiagnosticsRequest)(nil),  // 4: sysml.DiagnosticsRequest
	(*DiagnosticsResponse)(nil), // 5: sysml.DiagnosticsResponse
	(*SymbolInfo)(nil),          // 6: sysml.SymbolInfo
	(*AttributeInfo)(nil),       // 7: sysml.AttributeInfo
	(*Value)(nil),               // 8: sysml.Value
	(*Diagnostic)(nil),          // 9: sysml.Diagnostic
	(*Span)(nil),                // 10: sysml.Span
	nil,                         // 11: sysml.SymbolInfo.MetadataEntry
}
var file_sysml_proto_depIdxs = []int32{
	6,  // 0: sysml.ParseFileResponse.root:type_name -> sysml.SymbolInfo
	9,  // 1: sysml.ParseFileResponse.diagnostics:type_name -> sysml.Diagnostic
	6,  // 2: sysml.SymbolResponse.symbol:type_name -> sysml.SymbolInfo
	9,  // 3: sysml.DiagnosticsResponse.diagnostics:type_name -> sysml.Diagnostic
	11, // 4: sysml.SymbolInfo.metadata:type_name -> sysml.SymbolInfo.MetadataEntry
	7,  // 5: sysml.SymbolInfo.attributes:type_name -> sysml.AttributeInfo
	8,  // 6: sysml.AttributeInfo.value:type_name -> sysml.Value
	10, // 7: sysml.Diagnostic.span:type_name -> sysml.Span
	0,  // 8: sysml.SysMLService.ParseFile:input_type -> sysml.ParseFileRequest
	2,  // 9: sysml.SysMLService.GetSymbol:input_type -> sysml.GetSymbolRequest
	4,  // 10: sysml.SysMLService.GetDiagnostics:input_type -> sysml.DiagnosticsRequest
	1,  // 11: sysml.SysMLService.ParseFile:output_type -> sysml.ParseFileResponse
	3,  // 12: sysml.SysMLService.GetSymbol:output_type -> sysml.SymbolResponse
	5,  // 13: sysml.SysMLService.GetDiagnostics:output_type -> sysml.DiagnosticsResponse
	11, // [11:14] is the sub-list for method output_type
	8,  // [8:11] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_sysml_proto_init() }
func file_sysml_proto_init() {
	if File_sysml_proto != nil {
		return
	}
	file_sysml_proto_msgTypes[0].OneofWrappers = []any{
		(*ParseFileRequest_FilePath)(nil),
		(*ParseFileRequest_Content)(nil),
	}
	file_sysml_proto_msgTypes[8].OneofWrappers = []any{
		(*Value_Number)(nil),
		(*Value_Text)(nil),
		(*Value_Boolean)(nil),
		(*Value_Integer)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sysml_proto_rawDesc), len(file_sysml_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sysml_proto_goTypes,
		DependencyIndexes: file_sysml_proto_depIdxs,
		MessageInfos:      file_sysml_proto_msgTypes,
	}.Build()
	File_sysml_proto = out.File
	file_sysml_proto_goTypes = nil
	file_sysml_proto_depIdxs = nil
}
