// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.19.6
// source: sysml.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SysMLService_ParseFile_FullMethodName      = "/sysml.SysMLService/ParseFile"
	SysMLService_GetSymbol_FullMethodName      = "/sysml.SysMLService/GetSymbol"
	SysMLService_GetDiagnostics_FullMethodName = "/sysml.SysMLService/GetDiagnostics"
)

// SysMLServiceClient is the client API for SysMLService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SysMLService provides programmatic access to Systemica's parser and runtime
type SysMLServiceClient interface {
	// Parse a SysML file and return model hash for subsequent queries
	ParseFile(ctx context.Context, in *ParseFileRequest, opts ...grpc.CallOption) (*ParseFileResponse, error)
	// Get symbol information by qualified name
	GetSymbol(ctx context.Context, in *GetSymbolRequest, opts ...grpc.CallOption) (*SymbolResponse, error)
	// Get all diagnostics for a parsed model
	GetDiagnostics(ctx context.Context, in *DiagnosticsRequest, opts ...grpc.CallOption) (*DiagnosticsResponse, error)
}

type sysMLServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSysMLServiceClient(cc grpc.ClientConnInterface) SysMLServiceClient {
	return &sysMLServiceClient{cc}
}

func (c *sysMLServiceClient) ParseFile(ctx context.Context, in *ParseFileRequest, opts ...grpc.CallOption) (*ParseFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ParseFileResponse)
	err := c.cc.Invoke(ctx, SysMLService_ParseFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysMLServiceClient) GetSymbol(ctx context.Context, in *GetSymbolRequest, opts ...grpc.CallOption) (*SymbolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SymbolResponse)
	err := c.cc.Invoke(ctx, SysMLService_GetSymbol_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysMLServiceClient) GetDiagnostics(ctx context.Context, in *DiagnosticsRequest, opts ...grpc.CallOption) (*DiagnosticsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DiagnosticsResponse)
	err := c.cc.Invoke(ctx, SysMLService_GetDiagnostics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SysMLServiceServer is the server API for SysMLService service.
// All implementations must embed UnimplementedSysMLServiceServer
// for forward compatibility.
//
// SysMLService provides programmatic access to Systemica's parser and runtime
type SysMLServiceServer interface {
	// Parse a SysML file and return model hash for subsequent queries
	ParseFile(context.Context, *ParseFileRequest) (*ParseFileResponse, error)
	// Get symbol information by qualified name
	GetSymbol(context.Context, *GetSymbolRequest) (*SymbolResponse, error)
	// Get all diagnostics for a parsed model
	GetDiagnostics(context.Context, *DiagnosticsRequest) (*DiagnosticsResponse, error)
	mustEmbedUnimplementedSysMLServiceServer()
}

// UnimplementedSysMLServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSysMLServiceServer struct{}

func (UnimplementedSysMLServiceServer) ParseFile(context.Context, *ParseFileRequest) (*ParseFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ParseFile not implemented")
}
func (UnimplementedSysMLServiceServer) GetSymbol(context.Context, *GetSymbolRequest) (*SymbolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSymbol not implemented")
}
func (UnimplementedSysMLServiceServer) GetDiagnostics(context.Context, *DiagnosticsRequest) (*DiagnosticsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDiagnostics not implemented")
}
func (UnimplementedSysMLServiceServer) mustEmbedUnimplementedSysMLServiceServer() {}
func (UnimplementedSysMLServiceServer) testEmbeddedByValue()                      {}

// UnsafeSysMLServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SysMLServiceServer will
// result in compilation errors.
type UnsafeSysMLServiceServer interface {
	mustEmbedUnimplementedSysMLServiceServer()
}

func RegisterSysMLServiceServer(s grpc.ServiceRegistrar, srv SysMLServiceServer) {
	// If the following call panics, it indicates UnimplementedSysMLServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SysMLService_ServiceDesc, srv)
}

func _SysMLService_ParseFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParseFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysMLServiceServer).ParseFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysMLService_ParseFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysMLServiceServer).ParseFile(ctx, req.(*ParseFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysMLService_GetSymbol_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSymbolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysMLServiceServer).GetSymbol(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysMLService_GetSymbol_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysMLServiceServer).GetSymbol(ctx, req.(*GetSymbolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysMLService_GetDiagnostics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiagnosticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysMLServiceServer).GetDiagnostics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysMLService_GetDiagnostics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysMLServiceServer).GetDiagnostics(ctx, req.(*DiagnosticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SysMLService_ServiceDesc is the grpc.ServiceDesc for SysMLService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SysMLService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sysml.SysMLService",
	HandlerType: (*SysMLServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ParseFile",
			Handler:    _SysMLService_ParseFile_Handler,
		},
		{
			MethodName: "GetSymbol",
			Handler:    _SysMLService_GetSymbol_Handler,
		},
		{
			MethodName: "GetDiagnostics",
			Handler:    _SysMLService_GetDiagnostics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sysml.proto",
}
