// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sysml.proto
// Protobuf Java Version: 4.33.1

package org.openmbee.opensysml.proto;

@com.google.protobuf.Generated
public interface ApplyEditsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sysml.ApplyEditsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * from ParseFile response
   * </pre>
   *
   * <code>string model_hash = 1 [json_name = "modelHash"];</code>
   * @return The modelHash.
   */
  java.lang.String getModelHash();
  /**
   * <pre>
   * from ParseFile response
   * </pre>
   *
   * <code>string model_hash = 1 [json_name = "modelHash"];</code>
   * @return The bytes for modelHash.
   */
  com.google.protobuf.ByteString
      getModelHashBytes();

  /**
   * <pre>
   * Edits to apply, all of them or none. Empty is rejected: it names no edit,
   * and answering with the unedited source would look like one was made.
   * </pre>
   *
   * <code>repeated .sysml.EditOperation operations = 2 [json_name = "operations"];</code>
   */
  java.util.List<org.openmbee.opensysml.proto.EditOperation> 
      getOperationsList();
  /**
   * <pre>
   * Edits to apply, all of them or none. Empty is rejected: it names no edit,
   * and answering with the unedited source would look like one was made.
   * </pre>
   *
   * <code>repeated .sysml.EditOperation operations = 2 [json_name = "operations"];</code>
   */
  org.openmbee.opensysml.proto.EditOperation getOperations(int index);
  /**
   * <pre>
   * Edits to apply, all of them or none. Empty is rejected: it names no edit,
   * and answering with the unedited source would look like one was made.
   * </pre>
   *
   * <code>repeated .sysml.EditOperation operations = 2 [json_name = "operations"];</code>
   */
  int getOperationsCount();
  /**
   * <pre>
   * Edits to apply, all of them or none. Empty is rejected: it names no edit,
   * and answering with the unedited source would look like one was made.
   * </pre>
   *
   * <code>repeated .sysml.EditOperation operations = 2 [json_name = "operations"];</code>
   */
  java.util.List<? extends org.openmbee.opensysml.proto.EditOperationOrBuilder> 
      getOperationsOrBuilderList();
  /**
   * <pre>
   * Edits to apply, all of them or none. Empty is rejected: it names no edit,
   * and answering with the unedited source would look like one was made.
   * </pre>
   *
   * <code>repeated .sysml.EditOperation operations = 2 [json_name = "operations"];</code>
   */
  org.openmbee.opensysml.proto.EditOperationOrBuilder getOperationsOrBuilder(
      int index);
}
