// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sysml.proto
// Protobuf Java Version: 4.33.1

package org.openmbee.opensysml.proto;

@com.google.protobuf.Generated
public interface ArrayOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sysml.Array)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated int64 dimensions = 1 [json_name = "dimensions"];</code>
   * @return A list containing the dimensions.
   */
  java.util.List<java.lang.Long> getDimensionsList();
  /**
   * <code>repeated int64 dimensions = 1 [json_name = "dimensions"];</code>
   * @return The count of dimensions.
   */
  int getDimensionsCount();
  /**
   * <code>repeated int64 dimensions = 1 [json_name = "dimensions"];</code>
   * @param index The index of the element to return.
   * @return The dimensions at the given index.
   */
  long getDimensions(int index);

  /**
   * <code>repeated .sysml.Value elements = 2 [json_name = "elements"];</code>
   */
  java.util.List<org.openmbee.opensysml.proto.Value> 
      getElementsList();
  /**
   * <code>repeated .sysml.Value elements = 2 [json_name = "elements"];</code>
   */
  org.openmbee.opensysml.proto.Value getElements(int index);
  /**
   * <code>repeated .sysml.Value elements = 2 [json_name = "elements"];</code>
   */
  int getElementsCount();
  /**
   * <code>repeated .sysml.Value elements = 2 [json_name = "elements"];</code>
   */
  java.util.List<? extends org.openmbee.opensysml.proto.ValueOrBuilder> 
      getElementsOrBuilderList();
  /**
   * <code>repeated .sysml.Value elements = 2 [json_name = "elements"];</code>
   */
  org.openmbee.opensysml.proto.ValueOrBuilder getElementsOrBuilder(
      int index);
}
