// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sysml.proto
// Protobuf Java Version: 4.33.1

package org.openmbee.opensysml.proto;

@com.google.protobuf.Generated
public interface EnumLiteralOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sysml.EnumLiteral)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * FQN of the literal's declaration ("D::Color::red"). Its identity.
   * </pre>
   *
   * <code>string literal_id = 1 [json_name = "literalId"];</code>
   * @return The literalId.
   */
  java.lang.String getLiteralId();
  /**
   * <pre>
   * FQN of the literal's declaration ("D::Color::red"). Its identity.
   * </pre>
   *
   * <code>string literal_id = 1 [json_name = "literalId"];</code>
   * @return The bytes for literalId.
   */
  com.google.protobuf.ByteString
      getLiteralIdBytes();

  /**
   * <pre>
   * FQN of the enumeration definition declaring it ("D::Color").
   * </pre>
   *
   * <code>string enumeration_id = 2 [json_name = "enumerationId"];</code>
   * @return The enumerationId.
   */
  java.lang.String getEnumerationId();
  /**
   * <pre>
   * FQN of the enumeration definition declaring it ("D::Color").
   * </pre>
   *
   * <code>string enumeration_id = 2 [json_name = "enumerationId"];</code>
   * @return The bytes for enumerationId.
   */
  com.google.protobuf.ByteString
      getEnumerationIdBytes();

  /**
   * <pre>
   * The literal as a reader writes it ("Color::red").
   * </pre>
   *
   * <code>string name = 3 [json_name = "name"];</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * The literal as a reader writes it ("Color::red").
   * </pre>
   *
   * <code>string name = 3 [json_name = "name"];</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
