// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sysml.proto
// Protobuf Java Version: 4.33.1

package org.openmbee.opensysml.proto;

@com.google.protobuf.Generated
public interface VectorOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sysml.Vector)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .sysml.Value components = 1 [json_name = "components"];</code>
   */
  java.util.List<org.openmbee.opensysml.proto.Value> 
      getComponentsList();
  /**
   * <code>repeated .sysml.Value components = 1 [json_name = "components"];</code>
   */
  org.openmbee.opensysml.proto.Value getComponents(int index);
  /**
   * <code>repeated .sysml.Value components = 1 [json_name = "components"];</code>
   */
  int getComponentsCount();
  /**
   * <code>repeated .sysml.Value components = 1 [json_name = "components"];</code>
   */
  java.util.List<? extends org.openmbee.opensysml.proto.ValueOrBuilder> 
      getComponentsOrBuilderList();
  /**
   * <code>repeated .sysml.Value components = 1 [json_name = "components"];</code>
   */
  org.openmbee.opensysml.proto.ValueOrBuilder getComponentsOrBuilder(
      int index);
}
