// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sysml.proto
// Protobuf Java Version: 4.33.1

package io.opensysml.proto;

/**
 * <pre>
 * ApplyEditsResponse carries the edited source, or says why nothing was edited.
 * </pre>
 *
 * Protobuf type {@code sysml.ApplyEditsResponse}
 */
@com.google.protobuf.Generated
public final class ApplyEditsResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:sysml.ApplyEditsResponse)
    ApplyEditsResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 1,
      /* suffix= */ "",
      "ApplyEditsResponse");
  }
  // Use ApplyEditsResponse.newBuilder() to construct.
  private ApplyEditsResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ApplyEditsResponse() {
    content_ = "";
    applied_ = java.util.Collections.emptyList();
    error_ = "";
    failure_ = 0;
    diagnostics_ = java.util.Collections.emptyList();
    referringElements_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.opensysml.proto.Sysml.internal_static_sysml_ApplyEditsResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.opensysml.proto.Sysml.internal_static_sysml_ApplyEditsResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.opensysml.proto.ApplyEditsResponse.class, io.opensysml.proto.ApplyEditsResponse.Builder.class);
  }

  public static final int CONTENT_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object content_ = "";
  /**
   * <pre>
   * The edited notation, byte-identical to the source outside the edited spans.
   * Empty when the edits were refused, so a refusal never writes a file.
   * </pre>
   *
   * <code>string content = 1 [json_name = "content"];</code>
   * @return The content.
   */
  @java.lang.Override
  public java.lang.String getContent() {
    java.lang.Object ref = content_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      content_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The edited notation, byte-identical to the source outside the edited spans.
   * Empty when the edits were refused, so a refusal never writes a file.
   * </pre>
   *
   * <code>string content = 1 [json_name = "content"];</code>
   * @return The bytes for content.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getContentBytes() {
    java.lang.Object ref = content_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      content_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int APPLIED_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<io.opensysml.proto.AppliedEdit> applied_;
  /**
   * <pre>
   * What each operation changed, in request order.
   * </pre>
   *
   * <code>repeated .sysml.AppliedEdit applied = 2 [json_name = "applied"];</code>
   */
  @java.lang.Override
  public java.util.List<io.opensysml.proto.AppliedEdit> getAppliedList() {
    return applied_;
  }
  /**
   * <pre>
   * What each operation changed, in request order.
   * </pre>
   *
   * <code>repeated .sysml.AppliedEdit applied = 2 [json_name = "applied"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends io.opensysml.proto.AppliedEditOrBuilder> 
      getAppliedOrBuilderList() {
    return applied_;
  }
  /**
   * <pre>
   * What each operation changed, in request order.
   * </pre>
   *
   * <code>repeated .sysml.AppliedEdit applied = 2 [json_name = "applied"];</code>
   */
  @java.lang.Override
  public int getAppliedCount() {
    return applied_.size();
  }
  /**
   * <pre>
   * What each operation changed, in request order.
   * </pre>
   *
   * <code>repeated .sysml.AppliedEdit applied = 2 [json_name = "applied"];</code>
   */
  @java.lang.Override
  public io.opensysml.proto.AppliedEdit getApplied(int index) {
    return applied_.get(index);
  }
  /**
   * <pre>
   * What each operation changed, in request order.
   * </pre>
   *
   * <code>repeated .sysml.AppliedEdit applied = 2 [json_name = "applied"];</code>
   */
  @java.lang.Override
  public io.opensysml.proto.AppliedEditOrBuilder getAppliedOrBuilder(
      int index) {
    return applied_.get(index);
  }

  public static final int ERROR_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object error_ = "";
  /**
   * <pre>
   * non-empty if the edits were refused; content is unset
   * </pre>
   *
   * <code>string error = 3 [json_name = "error"];</code>
   * @return The error.
   */
  @java.lang.Override
  public java.lang.String getError() {
    java.lang.Object ref = error_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      error_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * non-empty if the edits were refused; content is unset
   * </pre>
   *
   * <code>string error = 3 [json_name = "error"];</code>
   * @return The bytes for error.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getErrorBytes() {
    java.lang.Object ref = error_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      error_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FAILURE_FIELD_NUMBER = 4;
  private int failure_ = 0;
  /**
   * <pre>
   * Which kind of refusal `error` reports, so a client acts on the kind rather
   * than on the message text.
   * </pre>
   *
   * <code>.sysml.EditFailure failure = 4 [json_name = "failure"];</code>
   * @return The enum numeric value on the wire for failure.
   */
  @java.lang.Override public int getFailureValue() {
    return failure_;
  }
  /**
   * <pre>
   * Which kind of refusal `error` reports, so a client acts on the kind rather
   * than on the message text.
   * </pre>
   *
   * <code>.sysml.EditFailure failure = 4 [json_name = "failure"];</code>
   * @return The failure.
   */
  @java.lang.Override public io.opensysml.proto.EditFailure getFailure() {
    io.opensysml.proto.EditFailure result = io.opensysml.proto.EditFailure.forNumber(failure_);
    return result == null ? io.opensysml.proto.EditFailure.UNRECOGNIZED : result;
  }

  public static final int DIAGNOSTICS_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private java.util.List<io.opensysml.proto.Diagnostic> diagnostics_;
  /**
   * <pre>
   * Diagnostics behind a refusal: the parse errors of an unreadable new value,
   * or the errors the edited source was found to have.
   * </pre>
   *
   * <code>repeated .sysml.Diagnostic diagnostics = 5 [json_name = "diagnostics"];</code>
   */
  @java.lang.Override
  public java.util.List<io.opensysml.proto.Diagnostic> getDiagnosticsList() {
    return diagnostics_;
  }
  /**
   * <pre>
   * Diagnostics behind a refusal: the parse errors of an unreadable new value,
   * or the errors the edited source was found to have.
   * </pre>
   *
   * <code>repeated .sysml.Diagnostic diagnostics = 5 [json_name = "diagnostics"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends io.opensysml.proto.DiagnosticOrBuilder> 
      getDiagnosticsOrBuilderList() {
    return diagnostics_;
  }
  /**
   * <pre>
   * Diagnostics behind a refusal: the parse errors of an unreadable new value,
   * or the errors the edited source was found to have.
   * </pre>
   *
   * <code>repeated .sysml.Diagnostic diagnostics = 5 [json_name = "diagnostics"];</code>
   */
  @java.lang.Override
  public int getDiagnosticsCount() {
    return diagnostics_.size();
  }
  /**
   * <pre>
   * Diagnostics behind a refusal: the parse errors of an unreadable new value,
   * or the errors the edited source was found to have.
   * </pre>
   *
   * <code>repeated .sysml.Diagnostic diagnostics = 5 [json_name = "diagnostics"];</code>
   */
  @java.lang.Override
  public io.opensysml.proto.Diagnostic getDiagnostics(int index) {
    return diagnostics_.get(index);
  }
  /**
   * <pre>
   * Diagnostics behind a refusal: the parse errors of an unreadable new value,
   * or the errors the edited source was found to have.
   * </pre>
   *
   * <code>repeated .sysml.Diagnostic diagnostics = 5 [json_name = "diagnostics"];</code>
   */
  @java.lang.Override
  public io.opensysml.proto.DiagnosticOrBuilder getDiagnosticsOrBuilder(
      int index) {
    return diagnostics_.get(index);
  }

  public static final int REFERRING_ELEMENTS_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList referringElements_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <pre>
   * Where the references to a declaration whose rename was refused are made:
   * the FQN of each referring namespace.
   * </pre>
   *
   * <code>repeated string referring_elements = 6 [json_name = "referringElements"];</code>
   * @return A list containing the referringElements.
   */
  public com.google.protobuf.ProtocolStringList
      getReferringElementsList() {
    return referringElements_;
  }
  /**
   * <pre>
   * Where the references to a declaration whose rename was refused are made:
   * the FQN of each referring namespace.
   * </pre>
   *
   * <code>repeated string referring_elements = 6 [json_name = "referringElements"];</code>
   * @return The count of referringElements.
   */
  public int getReferringElementsCount() {
    return referringElements_.size();
  }
  /**
   * <pre>
   * Where the references to a declaration whose rename was refused are made:
   * the FQN of each referring namespace.
   * </pre>
   *
   * <code>repeated string referring_elements = 6 [json_name = "referringElements"];</code>
   * @param index The index of the element to return.
   * @return The referringElements at the given index.
   */
  public java.lang.String getReferringElements(int index) {
    return referringElements_.get(index);
  }
  /**
   * <pre>
   * Where the references to a declaration whose rename was refused are made:
   * the FQN of each referring namespace.
   * </pre>
   *
   * <code>repeated string referring_elements = 6 [json_name = "referringElements"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the referringElements at the given index.
   */
  public com.google.protobuf.ByteString
      getReferringElementsBytes(int index) {
    return referringElements_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(content_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, content_);
    }
    for (int i = 0; i < applied_.size(); i++) {
      output.writeMessage(2, applied_.get(i));
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(error_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, error_);
    }
    if (failure_ != io.opensysml.proto.EditFailure.EDIT_FAILURE_UNSPECIFIED.getNumber()) {
      output.writeEnum(4, failure_);
    }
    for (int i = 0; i < diagnostics_.size(); i++) {
      output.writeMessage(5, diagnostics_.get(i));
    }
    for (int i = 0; i < referringElements_.size(); i++) {
      com.google.protobuf.GeneratedMessage.writeString(output, 6, referringElements_.getRaw(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(content_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, content_);
    }
    for (int i = 0; i < applied_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, applied_.get(i));
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(error_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, error_);
    }
    if (failure_ != io.opensysml.proto.EditFailure.EDIT_FAILURE_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, failure_);
    }
    for (int i = 0; i < diagnostics_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, diagnostics_.get(i));
    }
    {
      int dataSize = 0;
      for (int i = 0; i < referringElements_.size(); i++) {
        dataSize += computeStringSizeNoTag(referringElements_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getReferringElementsList().size();
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.opensysml.proto.ApplyEditsResponse)) {
      return super.equals(obj);
    }
    io.opensysml.proto.ApplyEditsResponse other = (io.opensysml.proto.ApplyEditsResponse) obj;

    if (!getContent()
        .equals(other.getContent())) return false;
    if (!getAppliedList()
        .equals(other.getAppliedList())) return false;
    if (!getError()
        .equals(other.getError())) return false;
    if (failure_ != other.failure_) return false;
    if (!getDiagnosticsList()
        .equals(other.getDiagnosticsList())) return false;
    if (!getReferringElementsList()
        .equals(other.getReferringElementsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CONTENT_FIELD_NUMBER;
    hash = (53 * hash) + getContent().hashCode();
    if (getAppliedCount() > 0) {
      hash = (37 * hash) + APPLIED_FIELD_NUMBER;
      hash = (53 * hash) + getAppliedList().hashCode();
    }
    hash = (37 * hash) + ERROR_FIELD_NUMBER;
    hash = (53 * hash) + getError().hashCode();
    hash = (37 * hash) + FAILURE_FIELD_NUMBER;
    hash = (53 * hash) + failure_;
    if (getDiagnosticsCount() > 0) {
      hash = (37 * hash) + DIAGNOSTICS_FIELD_NUMBER;
      hash = (53 * hash) + getDiagnosticsList().hashCode();
    }
    if (getReferringElementsCount() > 0) {
      hash = (37 * hash) + REFERRING_ELEMENTS_FIELD_NUMBER;
      hash = (53 * hash) + getReferringElementsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.opensysml.proto.ApplyEditsResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.opensysml.proto.ApplyEditsResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.opensysml.proto.ApplyEditsResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.opensysml.proto.ApplyEditsResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.opensysml.proto.ApplyEditsResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.opensysml.proto.ApplyEditsResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.opensysml.proto.ApplyEditsResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.opensysml.proto.ApplyEditsResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.opensysml.proto.ApplyEditsResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.opensysml.proto.ApplyEditsResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.opensysml.proto.ApplyEditsResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.opensysml.proto.ApplyEditsResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.opensysml.proto.ApplyEditsResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * ApplyEditsResponse carries the edited source, or says why nothing was edited.
   * </pre>
   *
   * Protobuf type {@code sysml.ApplyEditsResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:sysml.ApplyEditsResponse)
      io.opensysml.proto.ApplyEditsResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.opensysml.proto.Sysml.internal_static_sysml_ApplyEditsResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.opensysml.proto.Sysml.internal_static_sysml_ApplyEditsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.opensysml.proto.ApplyEditsResponse.class, io.opensysml.proto.ApplyEditsResponse.Builder.class);
    }

    // Construct using io.opensysml.proto.ApplyEditsResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      content_ = "";
      if (appliedBuilder_ == null) {
        applied_ = java.util.Collections.emptyList();
      } else {
        applied_ = null;
        appliedBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      error_ = "";
      failure_ = 0;
      if (diagnosticsBuilder_ == null) {
        diagnostics_ = java.util.Collections.emptyList();
      } else {
        diagnostics_ = null;
        diagnosticsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000010);
      referringElements_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.opensysml.proto.Sysml.internal_static_sysml_ApplyEditsResponse_descriptor;
    }

    @java.lang.Override
    public io.opensysml.proto.ApplyEditsResponse getDefaultInstanceForType() {
      return io.opensysml.proto.ApplyEditsResponse.getDefaultInstance();
    }

    @java.lang.Override
    public io.opensysml.proto.ApplyEditsResponse build() {
      io.opensysml.proto.ApplyEditsResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.opensysml.proto.ApplyEditsResponse buildPartial() {
      io.opensysml.proto.ApplyEditsResponse result = new io.opensysml.proto.ApplyEditsResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(io.opensysml.proto.ApplyEditsResponse result) {
      if (appliedBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          applied_ = java.util.Collections.unmodifiableList(applied_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.applied_ = applied_;
      } else {
        result.applied_ = appliedBuilder_.build();
      }
      if (diagnosticsBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0)) {
          diagnostics_ = java.util.Collections.unmodifiableList(diagnostics_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.diagnostics_ = diagnostics_;
      } else {
        result.diagnostics_ = diagnosticsBuilder_.build();
      }
    }

    private void buildPartial0(io.opensysml.proto.ApplyEditsResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.content_ = content_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.error_ = error_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.failure_ = failure_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        referringElements_.makeImmutable();
        result.referringElements_ = referringElements_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.opensysml.proto.ApplyEditsResponse) {
        return mergeFrom((io.opensysml.proto.ApplyEditsResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.opensysml.proto.ApplyEditsResponse other) {
      if (other == io.opensysml.proto.ApplyEditsResponse.getDefaultInstance()) return this;
      if (!other.getContent().isEmpty()) {
        content_ = other.content_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (appliedBuilder_ == null) {
        if (!other.applied_.isEmpty()) {
          if (applied_.isEmpty()) {
            applied_ = other.applied_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureAppliedIsMutable();
            applied_.addAll(other.applied_);
          }
          onChanged();
        }
      } else {
        if (!other.applied_.isEmpty()) {
          if (appliedBuilder_.isEmpty()) {
            appliedBuilder_.dispose();
            appliedBuilder_ = null;
            applied_ = other.applied_;
            bitField0_ = (bitField0_ & ~0x00000002);
            appliedBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetAppliedFieldBuilder() : null;
          } else {
            appliedBuilder_.addAllMessages(other.applied_);
          }
        }
      }
      if (!other.getError().isEmpty()) {
        error_ = other.error_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.failure_ != 0) {
        setFailureValue(other.getFailureValue());
      }
      if (diagnosticsBuilder_ == null) {
        if (!other.diagnostics_.isEmpty()) {
          if (diagnostics_.isEmpty()) {
            diagnostics_ = other.diagnostics_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureDiagnosticsIsMutable();
            diagnostics_.addAll(other.diagnostics_);
          }
          onChanged();
        }
      } else {
        if (!other.diagnostics_.isEmpty()) {
          if (diagnosticsBuilder_.isEmpty()) {
            diagnosticsBuilder_.dispose();
            diagnosticsBuilder_ = null;
            diagnostics_ = other.diagnostics_;
            bitField0_ = (bitField0_ & ~0x00000010);
            diagnosticsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetDiagnosticsFieldBuilder() : null;
          } else {
            diagnosticsBuilder_.addAllMessages(other.diagnostics_);
          }
        }
      }
      if (!other.referringElements_.isEmpty()) {
        if (referringElements_.isEmpty()) {
          referringElements_ = other.referringElements_;
          bitField0_ |= 0x00000020;
        } else {
          ensureReferringElementsIsMutable();
          referringElements_.addAll(other.referringElements_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              content_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              io.opensysml.proto.AppliedEdit m =
                  input.readMessage(
                      io.opensysml.proto.AppliedEdit.parser(),
                      extensionRegistry);
              if (appliedBuilder_ == null) {
                ensureAppliedIsMutable();
                applied_.add(m);
              } else {
                appliedBuilder_.addMessage(m);
              }
              break;
            } // case 18
            case 26: {
              error_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              failure_ = input.readEnum();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 42: {
              io.opensysml.proto.Diagnostic m =
                  input.readMessage(
                      io.opensysml.proto.Diagnostic.parser(),
                      extensionRegistry);
              if (diagnosticsBuilder_ == null) {
                ensureDiagnosticsIsMutable();
                diagnostics_.add(m);
              } else {
                diagnosticsBuilder_.addMessage(m);
              }
              break;
            } // case 42
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureReferringElementsIsMutable();
              referringElements_.add(s);
              break;
            } // case 50
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object content_ = "";
    /**
     * <pre>
     * The edited notation, byte-identical to the source outside the edited spans.
     * Empty when the edits were refused, so a refusal never writes a file.
     * </pre>
     *
     * <code>string content = 1 [json_name = "content"];</code>
     * @return The content.
     */
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        content_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The edited notation, byte-identical to the source outside the edited spans.
     * Empty when the edits were refused, so a refusal never writes a file.
     * </pre>
     *
     * <code>string content = 1 [json_name = "content"];</code>
     * @return The bytes for content.
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The edited notation, byte-identical to the source outside the edited spans.
     * Empty when the edits were refused, so a refusal never writes a file.
     * </pre>
     *
     * <code>string content = 1 [json_name = "content"];</code>
     * @param value The content to set.
     * @return This builder for chaining.
     */
    public Builder setContent(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      content_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The edited notation, byte-identical to the source outside the edited spans.
     * Empty when the edits were refused, so a refusal never writes a file.
     * </pre>
     *
     * <code>string content = 1 [json_name = "content"];</code>
     * @return This builder for chaining.
     */
    public Builder clearContent() {
      content_ = getDefaultInstance().getContent();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The edited notation, byte-identical to the source outside the edited spans.
     * Empty when the edits were refused, so a refusal never writes a file.
     * </pre>
     *
     * <code>string content = 1 [json_name = "content"];</code>
     * @param value The bytes for content to set.
     * @return This builder for chaining.
     */
    public Builder setContentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      content_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.util.List<io.opensysml.proto.AppliedEdit> applied_ =
      java.util.Collections.emptyList();
    private void ensureAppliedIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        applied_ = new java.util.ArrayList<io.opensysml.proto.AppliedEdit>(applied_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        io.opensysml.proto.AppliedEdit, io.opensysml.proto.AppliedEdit.Builder, io.opensysml.proto.AppliedEditOrBuilder> appliedBuilder_;

    /**
     * <pre>
     * What each operation changed, in request order.
     * </pre>
     *
     * <code>repeated .sysml.AppliedEdit applied = 2 [json_name = "applied"];</code>
     */
    public java.util.List<io.opensysml.proto.AppliedEdit> getAppliedList() {
      if (appliedBuilder_ == null) {
        return java.util.Collections.unmodifiableList(applied_);
      } else {
        return appliedBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * What each operation changed, in request order.
     * </pre>
     *
     * <code>repeated .sysml.AppliedEdit applied = 2 [json_name = "applied"];</code>
     */
    public int getAppliedCount() {
      if (appliedBuilder_ == null) {
        return applied_.size();
      } else {
        return appliedBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * What each operation changed, in request order.
     * </pre>
     *
     * <code>repeated .sysml.AppliedEdit applied = 2 [json_name = "applied"];</code>
     */
    public io.opensysml.proto.AppliedEdit getApplied(int index) {
      if (appliedBuilder_ == null) {
        return applied_.get(index);
      } else {
        return appliedBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * What each operation changed, in request order.
     * </pre>
     *
     * <code>repeated .sysml.AppliedEdit applied = 2 [json_name = "applied"];</code>
     */
    public Builder setApplied(
        int index, io.opensysml.proto.AppliedEdit value) {
      if (appliedBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAppliedIsMutable();
        applied_.set(index, value);
        onChanged();
      } else {
        appliedBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * What each operation changed, in request order.
     * </pre>
     *
     * <code>repeated .sysml.AppliedEdit applied = 2 [json_name = "applied"];</code>
     */
    public Builder setApplied(
        int index, io.opensysml.proto.AppliedEdit.Builder builderForValue) {
      if (appliedBuilder_ == null) {
        ensureAppliedIsMutable();
        applied_.set(index, builderForValue.build());
        onChanged();
      } else {
        appliedBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * What each operation changed, in request order.
     * </pre>
     *
     * <code>repeated .sysml.AppliedEdit applied = 2 [json_name = "applied"];</code>
     */
    public Builder addApplied(io.opensysml.proto.AppliedEdit value) {
      if (appliedBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAppliedIsMutable();
        applied_.add(value);
        onChanged();
      } else {
        appliedBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * What each operation changed, in request order.
     * </pre>
     *
     * <code>repeated .sysml.AppliedEdit applied = 2 [json_name = "applied"];</code>
     */
    public Builder addApplied(
        int index, io.opensysml.proto.AppliedEdit value) {
      if (appliedBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAppliedIsMutable();
        applied_.add(index, value);
        onChanged();
      } else {
        appliedBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * What each operation changed, in request order.
     * </pre>
     *
     * <code>repeated .sysml.AppliedEdit applied = 2 [json_name = "applied"];</code>
     */
    public Builder addApplied(
        io.opensysml.proto.AppliedEdit.Builder builderForValue) {
      if (appliedBuilder_ == null) {
        ensureAppliedIsMutable();
        applied_.add(builderForValue.build());
        onChanged();
      } else {
        appliedBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * What each operation changed, in request order.
     * </pre>
     *
     * <code>repeated .sysml.AppliedEdit applied = 2 [json_name = "applied"];</code>
     */
    public Builder addApplied(
        int index, io.opensysml.proto.AppliedEdit.Builder builderForValue) {
      if (appliedBuilder_ == null) {
        ensureAppliedIsMutable();
        applied_.add(index, builderForValue.build());
        onChanged();
      } else {
        appliedBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * What each operation changed, in request order.
     * </pre>
     *
     * <code>repeated .sysml.AppliedEdit applied = 2 [json_name = "applied"];</code>
     */
    public Builder addAllApplied(
        java.lang.Iterable<? extends io.opensysml.proto.AppliedEdit> values) {
      if (appliedBuilder_ == null) {
        ensureAppliedIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, applied_);
        onChanged();
      } else {
        appliedBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * What each operation changed, in request order.
     * </pre>
     *
     * <code>repeated .sysml.AppliedEdit applied = 2 [json_name = "applied"];</code>
     */
    public Builder clearApplied() {
      if (appliedBuilder_ == null) {
        applied_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        appliedBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * What each operation changed, in request order.
     * </pre>
     *
     * <code>repeated .sysml.AppliedEdit applied = 2 [json_name = "applied"];</code>
     */
    public Builder removeApplied(int index) {
      if (appliedBuilder_ == null) {
        ensureAppliedIsMutable();
        applied_.remove(index);
        onChanged();
      } else {
        appliedBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * What each operation changed, in request order.
     * </pre>
     *
     * <code>repeated .sysml.AppliedEdit applied = 2 [json_name = "applied"];</code>
     */
    public io.opensysml.proto.AppliedEdit.Builder getAppliedBuilder(
        int index) {
      return internalGetAppliedFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * What each operation changed, in request order.
     * </pre>
     *
     * <code>repeated .sysml.AppliedEdit applied = 2 [json_name = "applied"];</code>
     */
    public io.opensysml.proto.AppliedEditOrBuilder getAppliedOrBuilder(
        int index) {
      if (appliedBuilder_ == null) {
        return applied_.get(index);  } else {
        return appliedBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * What each operation changed, in request order.
     * </pre>
     *
     * <code>repeated .sysml.AppliedEdit applied = 2 [json_name = "applied"];</code>
     */
    public java.util.List<? extends io.opensysml.proto.AppliedEditOrBuilder> 
         getAppliedOrBuilderList() {
      if (appliedBuilder_ != null) {
        return appliedBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(applied_);
      }
    }
    /**
     * <pre>
     * What each operation changed, in request order.
     * </pre>
     *
     * <code>repeated .sysml.AppliedEdit applied = 2 [json_name = "applied"];</code>
     */
    public io.opensysml.proto.AppliedEdit.Builder addAppliedBuilder() {
      return internalGetAppliedFieldBuilder().addBuilder(
          io.opensysml.proto.AppliedEdit.getDefaultInstance());
    }
    /**
     * <pre>
     * What each operation changed, in request order.
     * </pre>
     *
     * <code>repeated .sysml.AppliedEdit applied = 2 [json_name = "applied"];</code>
     */
    public io.opensysml.proto.AppliedEdit.Builder addAppliedBuilder(
        int index) {
      return internalGetAppliedFieldBuilder().addBuilder(
          index, io.opensysml.proto.AppliedEdit.getDefaultInstance());
    }
    /**
     * <pre>
     * What each operation changed, in request order.
     * </pre>
     *
     * <code>repeated .sysml.AppliedEdit applied = 2 [json_name = "applied"];</code>
     */
    public java.util.List<io.opensysml.proto.AppliedEdit.Builder> 
         getAppliedBuilderList() {
      return internalGetAppliedFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        io.opensysml.proto.AppliedEdit, io.opensysml.proto.AppliedEdit.Builder, io.opensysml.proto.AppliedEditOrBuilder> 
        internalGetAppliedFieldBuilder() {
      if (appliedBuilder_ == null) {
        appliedBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            io.opensysml.proto.AppliedEdit, io.opensysml.proto.AppliedEdit.Builder, io.opensysml.proto.AppliedEditOrBuilder>(
                applied_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        applied_ = null;
      }
      return appliedBuilder_;
    }

    private java.lang.Object error_ = "";
    /**
     * <pre>
     * non-empty if the edits were refused; content is unset
     * </pre>
     *
     * <code>string error = 3 [json_name = "error"];</code>
     * @return The error.
     */
    public java.lang.String getError() {
      java.lang.Object ref = error_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        error_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * non-empty if the edits were refused; content is unset
     * </pre>
     *
     * <code>string error = 3 [json_name = "error"];</code>
     * @return The bytes for error.
     */
    public com.google.protobuf.ByteString
        getErrorBytes() {
      java.lang.Object ref = error_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        error_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * non-empty if the edits were refused; content is unset
     * </pre>
     *
     * <code>string error = 3 [json_name = "error"];</code>
     * @param value The error to set.
     * @return This builder for chaining.
     */
    public Builder setError(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      error_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * non-empty if the edits were refused; content is unset
     * </pre>
     *
     * <code>string error = 3 [json_name = "error"];</code>
     * @return This builder for chaining.
     */
    public Builder clearError() {
      error_ = getDefaultInstance().getError();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * non-empty if the edits were refused; content is unset
     * </pre>
     *
     * <code>string error = 3 [json_name = "error"];</code>
     * @param value The bytes for error to set.
     * @return This builder for chaining.
     */
    public Builder setErrorBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      error_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private int failure_ = 0;
    /**
     * <pre>
     * Which kind of refusal `error` reports, so a client acts on the kind rather
     * than on the message text.
     * </pre>
     *
     * <code>.sysml.EditFailure failure = 4 [json_name = "failure"];</code>
     * @return The enum numeric value on the wire for failure.
     */
    @java.lang.Override public int getFailureValue() {
      return failure_;
    }
    /**
     * <pre>
     * Which kind of refusal `error` reports, so a client acts on the kind rather
     * than on the message text.
     * </pre>
     *
     * <code>.sysml.EditFailure failure = 4 [json_name = "failure"];</code>
     * @param value The enum numeric value on the wire for failure to set.
     * @return This builder for chaining.
     */
    public Builder setFailureValue(int value) {
      failure_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Which kind of refusal `error` reports, so a client acts on the kind rather
     * than on the message text.
     * </pre>
     *
     * <code>.sysml.EditFailure failure = 4 [json_name = "failure"];</code>
     * @return The failure.
     */
    @java.lang.Override
    public io.opensysml.proto.EditFailure getFailure() {
      io.opensysml.proto.EditFailure result = io.opensysml.proto.EditFailure.forNumber(failure_);
      return result == null ? io.opensysml.proto.EditFailure.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * Which kind of refusal `error` reports, so a client acts on the kind rather
     * than on the message text.
     * </pre>
     *
     * <code>.sysml.EditFailure failure = 4 [json_name = "failure"];</code>
     * @param value The failure to set.
     * @return This builder for chaining.
     */
    public Builder setFailure(io.opensysml.proto.EditFailure value) {
      if (value == null) { throw new NullPointerException(); }
      bitField0_ |= 0x00000008;
      failure_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Which kind of refusal `error` reports, so a client acts on the kind rather
     * than on the message text.
     * </pre>
     *
     * <code>.sysml.EditFailure failure = 4 [json_name = "failure"];</code>
     * @return This builder for chaining.
     */
    public Builder clearFailure() {
      bitField0_ = (bitField0_ & ~0x00000008);
      failure_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<io.opensysml.proto.Diagnostic> diagnostics_ =
      java.util.Collections.emptyList();
    private void ensureDiagnosticsIsMutable() {
      if (!((bitField0_ & 0x00000010) != 0)) {
        diagnostics_ = new java.util.ArrayList<io.opensysml.proto.Diagnostic>(diagnostics_);
        bitField0_ |= 0x00000010;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        io.opensysml.proto.Diagnostic, io.opensysml.proto.Diagnostic.Builder, io.opensysml.proto.DiagnosticOrBuilder> diagnosticsBuilder_;

    /**
     * <pre>
     * Diagnostics behind a refusal: the parse errors of an unreadable new value,
     * or the errors the edited source was found to have.
     * </pre>
     *
     * <code>repeated .sysml.Diagnostic diagnostics = 5 [json_name = "diagnostics"];</code>
     */
    public java.util.List<io.opensysml.proto.Diagnostic> getDiagnosticsList() {
      if (diagnosticsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(diagnostics_);
      } else {
        return diagnosticsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * Diagnostics behind a refusal: the parse errors of an unreadable new value,
     * or the errors the edited source was found to have.
     * </pre>
     *
     * <code>repeated .sysml.Diagnostic diagnostics = 5 [json_name = "diagnostics"];</code>
     */
    public int getDiagnosticsCount() {
      if (diagnosticsBuilder_ == null) {
        return diagnostics_.size();
      } else {
        return diagnosticsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * Diagnostics behind a refusal: the parse errors of an unreadable new value,
     * or the errors the edited source was found to have.
     * </pre>
     *
     * <code>repeated .sysml.Diagnostic diagnostics = 5 [json_name = "diagnostics"];</code>
     */
    public io.opensysml.proto.Diagnostic getDiagnostics(int index) {
      if (diagnosticsBuilder_ == null) {
        return diagnostics_.get(index);
      } else {
        return diagnosticsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * Diagnostics behind a refusal: the parse errors of an unreadable new value,
     * or the errors the edited source was found to have.
     * </pre>
     *
     * <code>repeated .sysml.Diagnostic diagnostics = 5 [json_name = "diagnostics"];</code>
     */
    public Builder setDiagnostics(
        int index, io.opensysml.proto.Diagnostic value) {
      if (diagnosticsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDiagnosticsIsMutable();
        diagnostics_.set(index, value);
        onChanged();
      } else {
        diagnosticsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Diagnostics behind a refusal: the parse errors of an unreadable new value,
     * or the errors the edited source was found to have.
     * </pre>
     *
     * <code>repeated .sysml.Diagnostic diagnostics = 5 [json_name = "diagnostics"];</code>
     */
    public Builder setDiagnostics(
        int index, io.opensysml.proto.Diagnostic.Builder builderForValue) {
      if (diagnosticsBuilder_ == null) {
        ensureDiagnosticsIsMutable();
        diagnostics_.set(index, builderForValue.build());
        onChanged();
      } else {
        diagnosticsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Diagnostics behind a refusal: the parse errors of an unreadable new value,
     * or the errors the edited source was found to have.
     * </pre>
     *
     * <code>repeated .sysml.Diagnostic diagnostics = 5 [json_name = "diagnostics"];</code>
     */
    public Builder addDiagnostics(io.opensysml.proto.Diagnostic value) {
      if (diagnosticsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDiagnosticsIsMutable();
        diagnostics_.add(value);
        onChanged();
      } else {
        diagnosticsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * Diagnostics behind a refusal: the parse errors of an unreadable new value,
     * or the errors the edited source was found to have.
     * </pre>
     *
     * <code>repeated .sysml.Diagnostic diagnostics = 5 [json_name = "diagnostics"];</code>
     */
    public Builder addDiagnostics(
        int index, io.opensysml.proto.Diagnostic value) {
      if (diagnosticsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDiagnosticsIsMutable();
        diagnostics_.add(index, value);
        onChanged();
      } else {
        diagnosticsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Diagnostics behind a refusal: the parse errors of an unreadable new value,
     * or the errors the edited source was found to have.
     * </pre>
     *
     * <code>repeated .sysml.Diagnostic diagnostics = 5 [json_name = "diagnostics"];</code>
     */
    public Builder addDiagnostics(
        io.opensysml.proto.Diagnostic.Builder builderForValue) {
      if (diagnosticsBuilder_ == null) {
        ensureDiagnosticsIsMutable();
        diagnostics_.add(builderForValue.build());
        onChanged();
      } else {
        diagnosticsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Diagnostics behind a refusal: the parse errors of an unreadable new value,
     * or the errors the edited source was found to have.
     * </pre>
     *
     * <code>repeated .sysml.Diagnostic diagnostics = 5 [json_name = "diagnostics"];</code>
     */
    public Builder addDiagnostics(
        int index, io.opensysml.proto.Diagnostic.Builder builderForValue) {
      if (diagnosticsBuilder_ == null) {
        ensureDiagnosticsIsMutable();
        diagnostics_.add(index, builderForValue.build());
        onChanged();
      } else {
        diagnosticsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Diagnostics behind a refusal: the parse errors of an unreadable new value,
     * or the errors the edited source was found to have.
     * </pre>
     *
     * <code>repeated .sysml.Diagnostic diagnostics = 5 [json_name = "diagnostics"];</code>
     */
    public Builder addAllDiagnostics(
        java.lang.Iterable<? extends io.opensysml.proto.Diagnostic> values) {
      if (diagnosticsBuilder_ == null) {
        ensureDiagnosticsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, diagnostics_);
        onChanged();
      } else {
        diagnosticsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * Diagnostics behind a refusal: the parse errors of an unreadable new value,
     * or the errors the edited source was found to have.
     * </pre>
     *
     * <code>repeated .sysml.Diagnostic diagnostics = 5 [json_name = "diagnostics"];</code>
     */
    public Builder clearDiagnostics() {
      if (diagnosticsBuilder_ == null) {
        diagnostics_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
      } else {
        diagnosticsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Diagnostics behind a refusal: the parse errors of an unreadable new value,
     * or the errors the edited source was found to have.
     * </pre>
     *
     * <code>repeated .sysml.Diagnostic diagnostics = 5 [json_name = "diagnostics"];</code>
     */
    public Builder removeDiagnostics(int index) {
      if (diagnosticsBuilder_ == null) {
        ensureDiagnosticsIsMutable();
        diagnostics_.remove(index);
        onChanged();
      } else {
        diagnosticsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * Diagnostics behind a refusal: the parse errors of an unreadable new value,
     * or the errors the edited source was found to have.
     * </pre>
     *
     * <code>repeated .sysml.Diagnostic diagnostics = 5 [json_name = "diagnostics"];</code>
     */
    public io.opensysml.proto.Diagnostic.Builder getDiagnosticsBuilder(
        int index) {
      return internalGetDiagnosticsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * Diagnostics behind a refusal: the parse errors of an unreadable new value,
     * or the errors the edited source was found to have.
     * </pre>
     *
     * <code>repeated .sysml.Diagnostic diagnostics = 5 [json_name = "diagnostics"];</code>
     */
    public io.opensysml.proto.DiagnosticOrBuilder getDiagnosticsOrBuilder(
        int index) {
      if (diagnosticsBuilder_ == null) {
        return diagnostics_.get(index);  } else {
        return diagnosticsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * Diagnostics behind a refusal: the parse errors of an unreadable new value,
     * or the errors the edited source was found to have.
     * </pre>
     *
     * <code>repeated .sysml.Diagnostic diagnostics = 5 [json_name = "diagnostics"];</code>
     */
    public java.util.List<? extends io.opensysml.proto.DiagnosticOrBuilder> 
         getDiagnosticsOrBuilderList() {
      if (diagnosticsBuilder_ != null) {
        return diagnosticsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(diagnostics_);
      }
    }
    /**
     * <pre>
     * Diagnostics behind a refusal: the parse errors of an unreadable new value,
     * or the errors the edited source was found to have.
     * </pre>
     *
     * <code>repeated .sysml.Diagnostic diagnostics = 5 [json_name = "diagnostics"];</code>
     */
    public io.opensysml.proto.Diagnostic.Builder addDiagnosticsBuilder() {
      return internalGetDiagnosticsFieldBuilder().addBuilder(
          io.opensysml.proto.Diagnostic.getDefaultInstance());
    }
    /**
     * <pre>
     * Diagnostics behind a refusal: the parse errors of an unreadable new value,
     * or the errors the edited source was found to have.
     * </pre>
     *
     * <code>repeated .sysml.Diagnostic diagnostics = 5 [json_name = "diagnostics"];</code>
     */
    public io.opensysml.proto.Diagnostic.Builder addDiagnosticsBuilder(
        int index) {
      return internalGetDiagnosticsFieldBuilder().addBuilder(
          index, io.opensysml.proto.Diagnostic.getDefaultInstance());
    }
    /**
     * <pre>
     * Diagnostics behind a refusal: the parse errors of an unreadable new value,
     * or the errors the edited source was found to have.
     * </pre>
     *
     * <code>repeated .sysml.Diagnostic diagnostics = 5 [json_name = "diagnostics"];</code>
     */
    public java.util.List<io.opensysml.proto.Diagnostic.Builder> 
         getDiagnosticsBuilderList() {
      return internalGetDiagnosticsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        io.opensysml.proto.Diagnostic, io.opensysml.proto.Diagnostic.Builder, io.opensysml.proto.DiagnosticOrBuilder> 
        internalGetDiagnosticsFieldBuilder() {
      if (diagnosticsBuilder_ == null) {
        diagnosticsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            io.opensysml.proto.Diagnostic, io.opensysml.proto.Diagnostic.Builder, io.opensysml.proto.DiagnosticOrBuilder>(
                diagnostics_,
                ((bitField0_ & 0x00000010) != 0),
                getParentForChildren(),
                isClean());
        diagnostics_ = null;
      }
      return diagnosticsBuilder_;
    }

    private com.google.protobuf.LazyStringArrayList referringElements_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureReferringElementsIsMutable() {
      if (!referringElements_.isModifiable()) {
        referringElements_ = new com.google.protobuf.LazyStringArrayList(referringElements_);
      }
      bitField0_ |= 0x00000020;
    }
    /**
     * <pre>
     * Where the references to a declaration whose rename was refused are made:
     * the FQN of each referring namespace.
     * </pre>
     *
     * <code>repeated string referring_elements = 6 [json_name = "referringElements"];</code>
     * @return A list containing the referringElements.
     */
    public com.google.protobuf.ProtocolStringList
        getReferringElementsList() {
      referringElements_.makeImmutable();
      return referringElements_;
    }
    /**
     * <pre>
     * Where the references to a declaration whose rename was refused are made:
     * the FQN of each referring namespace.
     * </pre>
     *
     * <code>repeated string referring_elements = 6 [json_name = "referringElements"];</code>
     * @return The count of referringElements.
     */
    public int getReferringElementsCount() {
      return referringElements_.size();
    }
    /**
     * <pre>
     * Where the references to a declaration whose rename was refused are made:
     * the FQN of each referring namespace.
     * </pre>
     *
     * <code>repeated string referring_elements = 6 [json_name = "referringElements"];</code>
     * @param index The index of the element to return.
     * @return The referringElements at the given index.
     */
    public java.lang.String getReferringElements(int index) {
      return referringElements_.get(index);
    }
    /**
     * <pre>
     * Where the references to a declaration whose rename was refused are made:
     * the FQN of each referring namespace.
     * </pre>
     *
     * <code>repeated string referring_elements = 6 [json_name = "referringElements"];</code>
     * @param index The index of the value to return.
     * @return The bytes of the referringElements at the given index.
     */
    public com.google.protobuf.ByteString
        getReferringElementsBytes(int index) {
      return referringElements_.getByteString(index);
    }
    /**
     * <pre>
     * Where the references to a declaration whose rename was refused are made:
     * the FQN of each referring namespace.
     * </pre>
     *
     * <code>repeated string referring_elements = 6 [json_name = "referringElements"];</code>
     * @param index The index to set the value at.
     * @param value The referringElements to set.
     * @return This builder for chaining.
     */
    public Builder setReferringElements(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureReferringElementsIsMutable();
      referringElements_.set(index, value);
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Where the references to a declaration whose rename was refused are made:
     * the FQN of each referring namespace.
     * </pre>
     *
     * <code>repeated string referring_elements = 6 [json_name = "referringElements"];</code>
     * @param value The referringElements to add.
     * @return This builder for chaining.
     */
    public Builder addReferringElements(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureReferringElementsIsMutable();
      referringElements_.add(value);
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Where the references to a declaration whose rename was refused are made:
     * the FQN of each referring namespace.
     * </pre>
     *
     * <code>repeated string referring_elements = 6 [json_name = "referringElements"];</code>
     * @param values The referringElements to add.
     * @return This builder for chaining.
     */
    public Builder addAllReferringElements(
        java.lang.Iterable<java.lang.String> values) {
      ensureReferringElementsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, referringElements_);
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Where the references to a declaration whose rename was refused are made:
     * the FQN of each referring namespace.
     * </pre>
     *
     * <code>repeated string referring_elements = 6 [json_name = "referringElements"];</code>
     * @return This builder for chaining.
     */
    public Builder clearReferringElements() {
      referringElements_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000020);;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Where the references to a declaration whose rename was refused are made:
     * the FQN of each referring namespace.
     * </pre>
     *
     * <code>repeated string referring_elements = 6 [json_name = "referringElements"];</code>
     * @param value The bytes of the referringElements to add.
     * @return This builder for chaining.
     */
    public Builder addReferringElementsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureReferringElementsIsMutable();
      referringElements_.add(value);
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:sysml.ApplyEditsResponse)
  }

  // @@protoc_insertion_point(class_scope:sysml.ApplyEditsResponse)
  private static final io.opensysml.proto.ApplyEditsResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.opensysml.proto.ApplyEditsResponse();
  }

  public static io.opensysml.proto.ApplyEditsResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ApplyEditsResponse>
      PARSER = new com.google.protobuf.AbstractParser<ApplyEditsResponse>() {
    @java.lang.Override
    public ApplyEditsResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ApplyEditsResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ApplyEditsResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.opensysml.proto.ApplyEditsResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

