// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sysml.proto
// Protobuf Java Version: 4.33.1

package io.opensysml.proto;

/**
 * <pre>
 * ApplyEditsRequest asks for a model's source with edits applied to it. The
 * source edited is the one parse read, named by its hash, so an edit is applied
 * to the model that was inspected.
 * </pre>
 *
 * Protobuf type {@code sysml.ApplyEditsRequest}
 */
@com.google.protobuf.Generated
public final class ApplyEditsRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:sysml.ApplyEditsRequest)
    ApplyEditsRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 1,
      /* suffix= */ "",
      "ApplyEditsRequest");
  }
  // Use ApplyEditsRequest.newBuilder() to construct.
  private ApplyEditsRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ApplyEditsRequest() {
    modelHash_ = "";
    operations_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.opensysml.proto.Sysml.internal_static_sysml_ApplyEditsRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.opensysml.proto.Sysml.internal_static_sysml_ApplyEditsRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.opensysml.proto.ApplyEditsRequest.class, io.opensysml.proto.ApplyEditsRequest.Builder.class);
  }

  public static final int MODEL_HASH_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object modelHash_ = "";
  /**
   * <pre>
   * from ParseFile response
   * </pre>
   *
   * <code>string model_hash = 1 [json_name = "modelHash"];</code>
   * @return The modelHash.
   */
  @java.lang.Override
  public java.lang.String getModelHash() {
    java.lang.Object ref = modelHash_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      modelHash_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * from ParseFile response
   * </pre>
   *
   * <code>string model_hash = 1 [json_name = "modelHash"];</code>
   * @return The bytes for modelHash.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getModelHashBytes() {
    java.lang.Object ref = modelHash_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      modelHash_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OPERATIONS_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<io.opensysml.proto.EditOperation> operations_;
  /**
   * <pre>
   * Edits to apply, all of them or none. Empty is rejected: it names no edit,
   * and answering with the unedited source would look like one was made.
   * </pre>
   *
   * <code>repeated .sysml.EditOperation operations = 2 [json_name = "operations"];</code>
   */
  @java.lang.Override
  public java.util.List<io.opensysml.proto.EditOperation> getOperationsList() {
    return operations_;
  }
  /**
   * <pre>
   * Edits to apply, all of them or none. Empty is rejected: it names no edit,
   * and answering with the unedited source would look like one was made.
   * </pre>
   *
   * <code>repeated .sysml.EditOperation operations = 2 [json_name = "operations"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends io.opensysml.proto.EditOperationOrBuilder> 
      getOperationsOrBuilderList() {
    return operations_;
  }
  /**
   * <pre>
   * Edits to apply, all of them or none. Empty is rejected: it names no edit,
   * and answering with the unedited source would look like one was made.
   * </pre>
   *
   * <code>repeated .sysml.EditOperation operations = 2 [json_name = "operations"];</code>
   */
  @java.lang.Override
  public int getOperationsCount() {
    return operations_.size();
  }
  /**
   * <pre>
   * Edits to apply, all of them or none. Empty is rejected: it names no edit,
   * and answering with the unedited source would look like one was made.
   * </pre>
   *
   * <code>repeated .sysml.EditOperation operations = 2 [json_name = "operations"];</code>
   */
  @java.lang.Override
  public io.opensysml.proto.EditOperation getOperations(int index) {
    return operations_.get(index);
  }
  /**
   * <pre>
   * Edits to apply, all of them or none. Empty is rejected: it names no edit,
   * and answering with the unedited source would look like one was made.
   * </pre>
   *
   * <code>repeated .sysml.EditOperation operations = 2 [json_name = "operations"];</code>
   */
  @java.lang.Override
  public io.opensysml.proto.EditOperationOrBuilder getOperationsOrBuilder(
      int index) {
    return operations_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(modelHash_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, modelHash_);
    }
    for (int i = 0; i < operations_.size(); i++) {
      output.writeMessage(2, operations_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(modelHash_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, modelHash_);
    }
    for (int i = 0; i < operations_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, operations_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.opensysml.proto.ApplyEditsRequest)) {
      return super.equals(obj);
    }
    io.opensysml.proto.ApplyEditsRequest other = (io.opensysml.proto.ApplyEditsRequest) obj;

    if (!getModelHash()
        .equals(other.getModelHash())) return false;
    if (!getOperationsList()
        .equals(other.getOperationsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MODEL_HASH_FIELD_NUMBER;
    hash = (53 * hash) + getModelHash().hashCode();
    if (getOperationsCount() > 0) {
      hash = (37 * hash) + OPERATIONS_FIELD_NUMBER;
      hash = (53 * hash) + getOperationsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.opensysml.proto.ApplyEditsRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.opensysml.proto.ApplyEditsRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.opensysml.proto.ApplyEditsRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.opensysml.proto.ApplyEditsRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.opensysml.proto.ApplyEditsRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.opensysml.proto.ApplyEditsRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.opensysml.proto.ApplyEditsRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.opensysml.proto.ApplyEditsRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.opensysml.proto.ApplyEditsRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.opensysml.proto.ApplyEditsRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.opensysml.proto.ApplyEditsRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.opensysml.proto.ApplyEditsRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.opensysml.proto.ApplyEditsRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * ApplyEditsRequest asks for a model's source with edits applied to it. The
   * source edited is the one parse read, named by its hash, so an edit is applied
   * to the model that was inspected.
   * </pre>
   *
   * Protobuf type {@code sysml.ApplyEditsRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:sysml.ApplyEditsRequest)
      io.opensysml.proto.ApplyEditsRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.opensysml.proto.Sysml.internal_static_sysml_ApplyEditsRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.opensysml.proto.Sysml.internal_static_sysml_ApplyEditsRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.opensysml.proto.ApplyEditsRequest.class, io.opensysml.proto.ApplyEditsRequest.Builder.class);
    }

    // Construct using io.opensysml.proto.ApplyEditsRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      modelHash_ = "";
      if (operationsBuilder_ == null) {
        operations_ = java.util.Collections.emptyList();
      } else {
        operations_ = null;
        operationsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.opensysml.proto.Sysml.internal_static_sysml_ApplyEditsRequest_descriptor;
    }

    @java.lang.Override
    public io.opensysml.proto.ApplyEditsRequest getDefaultInstanceForType() {
      return io.opensysml.proto.ApplyEditsRequest.getDefaultInstance();
    }

    @java.lang.Override
    public io.opensysml.proto.ApplyEditsRequest build() {
      io.opensysml.proto.ApplyEditsRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.opensysml.proto.ApplyEditsRequest buildPartial() {
      io.opensysml.proto.ApplyEditsRequest result = new io.opensysml.proto.ApplyEditsRequest(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(io.opensysml.proto.ApplyEditsRequest result) {
      if (operationsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          operations_ = java.util.Collections.unmodifiableList(operations_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.operations_ = operations_;
      } else {
        result.operations_ = operationsBuilder_.build();
      }
    }

    private void buildPartial0(io.opensysml.proto.ApplyEditsRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.modelHash_ = modelHash_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.opensysml.proto.ApplyEditsRequest) {
        return mergeFrom((io.opensysml.proto.ApplyEditsRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.opensysml.proto.ApplyEditsRequest other) {
      if (other == io.opensysml.proto.ApplyEditsRequest.getDefaultInstance()) return this;
      if (!other.getModelHash().isEmpty()) {
        modelHash_ = other.modelHash_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (operationsBuilder_ == null) {
        if (!other.operations_.isEmpty()) {
          if (operations_.isEmpty()) {
            operations_ = other.operations_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureOperationsIsMutable();
            operations_.addAll(other.operations_);
          }
          onChanged();
        }
      } else {
        if (!other.operations_.isEmpty()) {
          if (operationsBuilder_.isEmpty()) {
            operationsBuilder_.dispose();
            operationsBuilder_ = null;
            operations_ = other.operations_;
            bitField0_ = (bitField0_ & ~0x00000002);
            operationsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetOperationsFieldBuilder() : null;
          } else {
            operationsBuilder_.addAllMessages(other.operations_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              modelHash_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              io.opensysml.proto.EditOperation m =
                  input.readMessage(
                      io.opensysml.proto.EditOperation.parser(),
                      extensionRegistry);
              if (operationsBuilder_ == null) {
                ensureOperationsIsMutable();
                operations_.add(m);
              } else {
                operationsBuilder_.addMessage(m);
              }
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object modelHash_ = "";
    /**
     * <pre>
     * from ParseFile response
     * </pre>
     *
     * <code>string model_hash = 1 [json_name = "modelHash"];</code>
     * @return The modelHash.
     */
    public java.lang.String getModelHash() {
      java.lang.Object ref = modelHash_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        modelHash_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * from ParseFile response
     * </pre>
     *
     * <code>string model_hash = 1 [json_name = "modelHash"];</code>
     * @return The bytes for modelHash.
     */
    public com.google.protobuf.ByteString
        getModelHashBytes() {
      java.lang.Object ref = modelHash_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        modelHash_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * from ParseFile response
     * </pre>
     *
     * <code>string model_hash = 1 [json_name = "modelHash"];</code>
     * @param value The modelHash to set.
     * @return This builder for chaining.
     */
    public Builder setModelHash(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      modelHash_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * from ParseFile response
     * </pre>
     *
     * <code>string model_hash = 1 [json_name = "modelHash"];</code>
     * @return This builder for chaining.
     */
    public Builder clearModelHash() {
      modelHash_ = getDefaultInstance().getModelHash();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * from ParseFile response
     * </pre>
     *
     * <code>string model_hash = 1 [json_name = "modelHash"];</code>
     * @param value The bytes for modelHash to set.
     * @return This builder for chaining.
     */
    public Builder setModelHashBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      modelHash_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.util.List<io.opensysml.proto.EditOperation> operations_ =
      java.util.Collections.emptyList();
    private void ensureOperationsIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        operations_ = new java.util.ArrayList<io.opensysml.proto.EditOperation>(operations_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        io.opensysml.proto.EditOperation, io.opensysml.proto.EditOperation.Builder, io.opensysml.proto.EditOperationOrBuilder> operationsBuilder_;

    /**
     * <pre>
     * Edits to apply, all of them or none. Empty is rejected: it names no edit,
     * and answering with the unedited source would look like one was made.
     * </pre>
     *
     * <code>repeated .sysml.EditOperation operations = 2 [json_name = "operations"];</code>
     */
    public java.util.List<io.opensysml.proto.EditOperation> getOperationsList() {
      if (operationsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(operations_);
      } else {
        return operationsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * Edits to apply, all of them or none. Empty is rejected: it names no edit,
     * and answering with the unedited source would look like one was made.
     * </pre>
     *
     * <code>repeated .sysml.EditOperation operations = 2 [json_name = "operations"];</code>
     */
    public int getOperationsCount() {
      if (operationsBuilder_ == null) {
        return operations_.size();
      } else {
        return operationsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * Edits to apply, all of them or none. Empty is rejected: it names no edit,
     * and answering with the unedited source would look like one was made.
     * </pre>
     *
     * <code>repeated .sysml.EditOperation operations = 2 [json_name = "operations"];</code>
     */
    public io.opensysml.proto.EditOperation getOperations(int index) {
      if (operationsBuilder_ == null) {
        return operations_.get(index);
      } else {
        return operationsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * Edits to apply, all of them or none. Empty is rejected: it names no edit,
     * and answering with the unedited source would look like one was made.
     * </pre>
     *
     * <code>repeated .sysml.EditOperation operations = 2 [json_name = "operations"];</code>
     */
    public Builder setOperations(
        int index, io.opensysml.proto.EditOperation value) {
      if (operationsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOperationsIsMutable();
        operations_.set(index, value);
        onChanged();
      } else {
        operationsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Edits to apply, all of them or none. Empty is rejected: it names no edit,
     * and answering with the unedited source would look like one was made.
     * </pre>
     *
     * <code>repeated .sysml.EditOperation operations = 2 [json_name = "operations"];</code>
     */
    public Builder setOperations(
        int index, io.opensysml.proto.EditOperation.Builder builderForValue) {
      if (operationsBuilder_ == null) {
        ensureOperationsIsMutable();
        operations_.set(index, builderForValue.build());
        onChanged();
      } else {
        operationsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Edits to apply, all of them or none. Empty is rejected: it names no edit,
     * and answering with the unedited source would look like one was made.
     * </pre>
     *
     * <code>repeated .sysml.EditOperation operations = 2 [json_name = "operations"];</code>
     */
    public Builder addOperations(io.opensysml.proto.EditOperation value) {
      if (operationsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOperationsIsMutable();
        operations_.add(value);
        onChanged();
      } else {
        operationsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * Edits to apply, all of them or none. Empty is rejected: it names no edit,
     * and answering with the unedited source would look like one was made.
     * </pre>
     *
     * <code>repeated .sysml.EditOperation operations = 2 [json_name = "operations"];</code>
     */
    public Builder addOperations(
        int index, io.opensysml.proto.EditOperation value) {
      if (operationsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOperationsIsMutable();
        operations_.add(index, value);
        onChanged();
      } else {
        operationsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Edits to apply, all of them or none. Empty is rejected: it names no edit,
     * and answering with the unedited source would look like one was made.
     * </pre>
     *
     * <code>repeated .sysml.EditOperation operations = 2 [json_name = "operations"];</code>
     */
    public Builder addOperations(
        io.opensysml.proto.EditOperation.Builder builderForValue) {
      if (operationsBuilder_ == null) {
        ensureOperationsIsMutable();
        operations_.add(builderForValue.build());
        onChanged();
      } else {
        operationsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Edits to apply, all of them or none. Empty is rejected: it names no edit,
     * and answering with the unedited source would look like one was made.
     * </pre>
     *
     * <code>repeated .sysml.EditOperation operations = 2 [json_name = "operations"];</code>
     */
    public Builder addOperations(
        int index, io.opensysml.proto.EditOperation.Builder builderForValue) {
      if (operationsBuilder_ == null) {
        ensureOperationsIsMutable();
        operations_.add(index, builderForValue.build());
        onChanged();
      } else {
        operationsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Edits to apply, all of them or none. Empty is rejected: it names no edit,
     * and answering with the unedited source would look like one was made.
     * </pre>
     *
     * <code>repeated .sysml.EditOperation operations = 2 [json_name = "operations"];</code>
     */
    public Builder addAllOperations(
        java.lang.Iterable<? extends io.opensysml.proto.EditOperation> values) {
      if (operationsBuilder_ == null) {
        ensureOperationsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, operations_);
        onChanged();
      } else {
        operationsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * Edits to apply, all of them or none. Empty is rejected: it names no edit,
     * and answering with the unedited source would look like one was made.
     * </pre>
     *
     * <code>repeated .sysml.EditOperation operations = 2 [json_name = "operations"];</code>
     */
    public Builder clearOperations() {
      if (operationsBuilder_ == null) {
        operations_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        operationsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Edits to apply, all of them or none. Empty is rejected: it names no edit,
     * and answering with the unedited source would look like one was made.
     * </pre>
     *
     * <code>repeated .sysml.EditOperation operations = 2 [json_name = "operations"];</code>
     */
    public Builder removeOperations(int index) {
      if (operationsBuilder_ == null) {
        ensureOperationsIsMutable();
        operations_.remove(index);
        onChanged();
      } else {
        operationsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * Edits to apply, all of them or none. Empty is rejected: it names no edit,
     * and answering with the unedited source would look like one was made.
     * </pre>
     *
     * <code>repeated .sysml.EditOperation operations = 2 [json_name = "operations"];</code>
     */
    public io.opensysml.proto.EditOperation.Builder getOperationsBuilder(
        int index) {
      return internalGetOperationsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * Edits to apply, all of them or none. Empty is rejected: it names no edit,
     * and answering with the unedited source would look like one was made.
     * </pre>
     *
     * <code>repeated .sysml.EditOperation operations = 2 [json_name = "operations"];</code>
     */
    public io.opensysml.proto.EditOperationOrBuilder getOperationsOrBuilder(
        int index) {
      if (operationsBuilder_ == null) {
        return operations_.get(index);  } else {
        return operationsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * Edits to apply, all of them or none. Empty is rejected: it names no edit,
     * and answering with the unedited source would look like one was made.
     * </pre>
     *
     * <code>repeated .sysml.EditOperation operations = 2 [json_name = "operations"];</code>
     */
    public java.util.List<? extends io.opensysml.proto.EditOperationOrBuilder> 
         getOperationsOrBuilderList() {
      if (operationsBuilder_ != null) {
        return operationsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(operations_);
      }
    }
    /**
     * <pre>
     * Edits to apply, all of them or none. Empty is rejected: it names no edit,
     * and answering with the unedited source would look like one was made.
     * </pre>
     *
     * <code>repeated .sysml.EditOperation operations = 2 [json_name = "operations"];</code>
     */
    public io.opensysml.proto.EditOperation.Builder addOperationsBuilder() {
      return internalGetOperationsFieldBuilder().addBuilder(
          io.opensysml.proto.EditOperation.getDefaultInstance());
    }
    /**
     * <pre>
     * Edits to apply, all of them or none. Empty is rejected: it names no edit,
     * and answering with the unedited source would look like one was made.
     * </pre>
     *
     * <code>repeated .sysml.EditOperation operations = 2 [json_name = "operations"];</code>
     */
    public io.opensysml.proto.EditOperation.Builder addOperationsBuilder(
        int index) {
      return internalGetOperationsFieldBuilder().addBuilder(
          index, io.opensysml.proto.EditOperation.getDefaultInstance());
    }
    /**
     * <pre>
     * Edits to apply, all of them or none. Empty is rejected: it names no edit,
     * and answering with the unedited source would look like one was made.
     * </pre>
     *
     * <code>repeated .sysml.EditOperation operations = 2 [json_name = "operations"];</code>
     */
    public java.util.List<io.opensysml.proto.EditOperation.Builder> 
         getOperationsBuilderList() {
      return internalGetOperationsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        io.opensysml.proto.EditOperation, io.opensysml.proto.EditOperation.Builder, io.opensysml.proto.EditOperationOrBuilder> 
        internalGetOperationsFieldBuilder() {
      if (operationsBuilder_ == null) {
        operationsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            io.opensysml.proto.EditOperation, io.opensysml.proto.EditOperation.Builder, io.opensysml.proto.EditOperationOrBuilder>(
                operations_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        operations_ = null;
      }
      return operationsBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:sysml.ApplyEditsRequest)
  }

  // @@protoc_insertion_point(class_scope:sysml.ApplyEditsRequest)
  private static final io.opensysml.proto.ApplyEditsRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.opensysml.proto.ApplyEditsRequest();
  }

  public static io.opensysml.proto.ApplyEditsRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ApplyEditsRequest>
      PARSER = new com.google.protobuf.AbstractParser<ApplyEditsRequest>() {
    @java.lang.Override
    public ApplyEditsRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ApplyEditsRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ApplyEditsRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.opensysml.proto.ApplyEditsRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

