// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sysml.proto
// Protobuf Java Version: 4.33.1

package io.opensysml.proto;

@com.google.protobuf.Generated
public interface ConstraintOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sysml.Constraint)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.sysml.PrimitiveConstraint primitive = 1 [json_name = "primitive"];</code>
   * @return Whether the primitive field is set.
   */
  boolean hasPrimitive();
  /**
   * <code>.sysml.PrimitiveConstraint primitive = 1 [json_name = "primitive"];</code>
   * @return The primitive.
   */
  io.opensysml.proto.PrimitiveConstraint getPrimitive();
  /**
   * <code>.sysml.PrimitiveConstraint primitive = 1 [json_name = "primitive"];</code>
   */
  io.opensysml.proto.PrimitiveConstraintOrBuilder getPrimitiveOrBuilder();

  /**
   * <code>.sysml.CompositeConstraint composite = 2 [json_name = "composite"];</code>
   * @return Whether the composite field is set.
   */
  boolean hasComposite();
  /**
   * <code>.sysml.CompositeConstraint composite = 2 [json_name = "composite"];</code>
   * @return The composite.
   */
  io.opensysml.proto.CompositeConstraint getComposite();
  /**
   * <code>.sysml.CompositeConstraint composite = 2 [json_name = "composite"];</code>
   */
  io.opensysml.proto.CompositeConstraintOrBuilder getCompositeOrBuilder();

  io.opensysml.proto.Constraint.ConstraintCase getConstraintCase();
}
