// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sysml.proto
// Protobuf Java Version: 4.33.1

package io.opensysml.proto;

@com.google.protobuf.Generated
public interface DiagnosticOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sysml.Diagnostic)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * "error", "warning", "info"
   * </pre>
   *
   * <code>string severity = 1 [json_name = "severity"];</code>
   * @return The severity.
   */
  java.lang.String getSeverity();
  /**
   * <pre>
   * "error", "warning", "info"
   * </pre>
   *
   * <code>string severity = 1 [json_name = "severity"];</code>
   * @return The bytes for severity.
   */
  com.google.protobuf.ByteString
      getSeverityBytes();

  /**
   * <code>string message = 2 [json_name = "message"];</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2 [json_name = "message"];</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>.sysml.Span span = 3 [json_name = "span"];</code>
   * @return Whether the span field is set.
   */
  boolean hasSpan();
  /**
   * <code>.sysml.Span span = 3 [json_name = "span"];</code>
   * @return The span.
   */
  io.opensysml.proto.Span getSpan();
  /**
   * <code>.sysml.Span span = 3 [json_name = "span"];</code>
   */
  io.opensysml.proto.SpanOrBuilder getSpanOrBuilder();
}
