// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sysml.proto
// Protobuf Java Version: 4.33.1

package io.opensysml.proto;

@com.google.protobuf.Generated
public interface DocumentQueryRowOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sysml.DocumentQueryRow)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The selected element itself, an element value with its qualified name.
   * </pre>
   *
   * <code>.sysml.DocumentValue element = 1 [json_name = "element"];</code>
   * @return Whether the element field is set.
   */
  boolean hasElement();
  /**
   * <pre>
   * The selected element itself, an element value with its qualified name.
   * </pre>
   *
   * <code>.sysml.DocumentValue element = 1 [json_name = "element"];</code>
   * @return The element.
   */
  io.opensysml.proto.DocumentValue getElement();
  /**
   * <pre>
   * The selected element itself, an element value with its qualified name.
   * </pre>
   *
   * <code>.sysml.DocumentValue element = 1 [json_name = "element"];</code>
   */
  io.opensysml.proto.DocumentValueOrBuilder getElementOrBuilder();

  /**
   * <code>repeated .sysml.DocumentQueryCell cells = 2 [json_name = "cells"];</code>
   */
  java.util.List<io.opensysml.proto.DocumentQueryCell> 
      getCellsList();
  /**
   * <code>repeated .sysml.DocumentQueryCell cells = 2 [json_name = "cells"];</code>
   */
  io.opensysml.proto.DocumentQueryCell getCells(int index);
  /**
   * <code>repeated .sysml.DocumentQueryCell cells = 2 [json_name = "cells"];</code>
   */
  int getCellsCount();
  /**
   * <code>repeated .sysml.DocumentQueryCell cells = 2 [json_name = "cells"];</code>
   */
  java.util.List<? extends io.opensysml.proto.DocumentQueryCellOrBuilder> 
      getCellsOrBuilderList();
  /**
   * <code>repeated .sysml.DocumentQueryCell cells = 2 [json_name = "cells"];</code>
   */
  io.opensysml.proto.DocumentQueryCellOrBuilder getCellsOrBuilder(
      int index);
}
