// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sysml.proto
// Protobuf Java Version: 4.33.1

package io.opensysml.proto;

@com.google.protobuf.Generated
public interface DocumentValueOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sysml.DocumentValue)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * qualified name of a model element
   * </pre>
   *
   * <code>string element_id = 1 [json_name = "elementId"];</code>
   * @return Whether the elementId field is set.
   */
  boolean hasElementId();
  /**
   * <pre>
   * qualified name of a model element
   * </pre>
   *
   * <code>string element_id = 1 [json_name = "elementId"];</code>
   * @return The elementId.
   */
  java.lang.String getElementId();
  /**
   * <pre>
   * qualified name of a model element
   * </pre>
   *
   * <code>string element_id = 1 [json_name = "elementId"];</code>
   * @return The bytes for elementId.
   */
  com.google.protobuf.ByteString
      getElementIdBytes();

  /**
   * <code>string string_value = 2 [json_name = "stringValue"];</code>
   * @return Whether the stringValue field is set.
   */
  boolean hasStringValue();
  /**
   * <code>string string_value = 2 [json_name = "stringValue"];</code>
   * @return The stringValue.
   */
  java.lang.String getStringValue();
  /**
   * <code>string string_value = 2 [json_name = "stringValue"];</code>
   * @return The bytes for stringValue.
   */
  com.google.protobuf.ByteString
      getStringValueBytes();

  /**
   * <code>int64 int_value = 3 [json_name = "intValue"];</code>
   * @return Whether the intValue field is set.
   */
  boolean hasIntValue();
  /**
   * <code>int64 int_value = 3 [json_name = "intValue"];</code>
   * @return The intValue.
   */
  long getIntValue();

  /**
   * <code>double real_value = 4 [json_name = "realValue"];</code>
   * @return Whether the realValue field is set.
   */
  boolean hasRealValue();
  /**
   * <code>double real_value = 4 [json_name = "realValue"];</code>
   * @return The realValue.
   */
  double getRealValue();

  /**
   * <code>bool bool_value = 5 [json_name = "boolValue"];</code>
   * @return Whether the boolValue field is set.
   */
  boolean hasBoolValue();
  /**
   * <code>bool bool_value = 5 [json_name = "boolValue"];</code>
   * @return The boolValue.
   */
  boolean getBoolValue();

  /**
   * <code>bool infinity = 6 [json_name = "infinity"];</code>
   * @return Whether the infinity field is set.
   */
  boolean hasInfinity();
  /**
   * <code>bool infinity = 6 [json_name = "infinity"];</code>
   * @return The infinity.
   */
  boolean getInfinity();

  /**
   * <pre>
   * Metamodel type of element_id ("PartUsage", ...); answered, ignored when bound.
   * </pre>
   *
   * <code>string element_type = 7 [json_name = "elementType"];</code>
   * @return The elementType.
   */
  java.lang.String getElementType();
  /**
   * <pre>
   * Metamodel type of element_id ("PartUsage", ...); answered, ignored when bound.
   * </pre>
   *
   * <code>string element_type = 7 [json_name = "elementType"];</code>
   * @return The bytes for elementType.
   */
  com.google.protobuf.ByteString
      getElementTypeBytes();

  io.opensysml.proto.DocumentValue.KindCase getKindCase();
}
