// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sysml.proto
// Protobuf Java Version: 4.33.1

package io.opensysml.proto;

@com.google.protobuf.Generated
public interface DocumentQueryCellOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sysml.DocumentQueryCell)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .sysml.DocumentValue values = 1 [json_name = "values"];</code>
   */
  java.util.List<io.opensysml.proto.DocumentValue> 
      getValuesList();
  /**
   * <code>repeated .sysml.DocumentValue values = 1 [json_name = "values"];</code>
   */
  io.opensysml.proto.DocumentValue getValues(int index);
  /**
   * <code>repeated .sysml.DocumentValue values = 1 [json_name = "values"];</code>
   */
  int getValuesCount();
  /**
   * <code>repeated .sysml.DocumentValue values = 1 [json_name = "values"];</code>
   */
  java.util.List<? extends io.opensysml.proto.DocumentValueOrBuilder> 
      getValuesOrBuilderList();
  /**
   * <code>repeated .sysml.DocumentValue values = 1 [json_name = "values"];</code>
   */
  io.opensysml.proto.DocumentValueOrBuilder getValuesOrBuilder(
      int index);
}
