// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sysml.proto
// Protobuf Java Version: 4.33.1

package io.opensysml.proto;

@com.google.protobuf.Generated
public interface EditOperationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sysml.EditOperation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.sysml.SetValueEdit set_value = 1 [json_name = "setValue"];</code>
   * @return Whether the setValue field is set.
   */
  boolean hasSetValue();
  /**
   * <code>.sysml.SetValueEdit set_value = 1 [json_name = "setValue"];</code>
   * @return The setValue.
   */
  io.opensysml.proto.SetValueEdit getSetValue();
  /**
   * <code>.sysml.SetValueEdit set_value = 1 [json_name = "setValue"];</code>
   */
  io.opensysml.proto.SetValueEditOrBuilder getSetValueOrBuilder();

  /**
   * <code>.sysml.RenameEdit rename = 2 [json_name = "rename"];</code>
   * @return Whether the rename field is set.
   */
  boolean hasRename();
  /**
   * <code>.sysml.RenameEdit rename = 2 [json_name = "rename"];</code>
   * @return The rename.
   */
  io.opensysml.proto.RenameEdit getRename();
  /**
   * <code>.sysml.RenameEdit rename = 2 [json_name = "rename"];</code>
   */
  io.opensysml.proto.RenameEditOrBuilder getRenameOrBuilder();

  /**
   * <code>.sysml.AddMemberEdit add_member = 3 [json_name = "addMember"];</code>
   * @return Whether the addMember field is set.
   */
  boolean hasAddMember();
  /**
   * <code>.sysml.AddMemberEdit add_member = 3 [json_name = "addMember"];</code>
   * @return The addMember.
   */
  io.opensysml.proto.AddMemberEdit getAddMember();
  /**
   * <code>.sysml.AddMemberEdit add_member = 3 [json_name = "addMember"];</code>
   */
  io.opensysml.proto.AddMemberEditOrBuilder getAddMemberOrBuilder();

  /**
   * <code>.sysml.DeleteEdit delete = 4 [json_name = "delete"];</code>
   * @return Whether the delete field is set.
   */
  boolean hasDelete();
  /**
   * <code>.sysml.DeleteEdit delete = 4 [json_name = "delete"];</code>
   * @return The delete.
   */
  io.opensysml.proto.DeleteEdit getDelete();
  /**
   * <code>.sysml.DeleteEdit delete = 4 [json_name = "delete"];</code>
   */
  io.opensysml.proto.DeleteEditOrBuilder getDeleteOrBuilder();

  io.opensysml.proto.EditOperation.OperationCase getOperationCase();
}
