// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sysml.proto
// Protobuf Java Version: 4.33.1

package io.opensysml.proto;

/**
 * <pre>
 * ExecuteStateRequest requests state machine execution
 * </pre>
 *
 * Protobuf type {@code sysml.ExecuteStateRequest}
 */
@com.google.protobuf.Generated
public final class ExecuteStateRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:sysml.ExecuteStateRequest)
    ExecuteStateRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 1,
      /* suffix= */ "",
      "ExecuteStateRequest");
  }
  // Use ExecuteStateRequest.newBuilder() to construct.
  private ExecuteStateRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ExecuteStateRequest() {
    modelHash_ = "";
    stateMachineSymbolId_ = "";
    events_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.opensysml.proto.Sysml.internal_static_sysml_ExecuteStateRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.opensysml.proto.Sysml.internal_static_sysml_ExecuteStateRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.opensysml.proto.ExecuteStateRequest.class, io.opensysml.proto.ExecuteStateRequest.Builder.class);
  }

  public static final int MODEL_HASH_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object modelHash_ = "";
  /**
   * <code>string model_hash = 1 [json_name = "modelHash"];</code>
   * @return The modelHash.
   */
  @java.lang.Override
  public java.lang.String getModelHash() {
    java.lang.Object ref = modelHash_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      modelHash_ = s;
      return s;
    }
  }
  /**
   * <code>string model_hash = 1 [json_name = "modelHash"];</code>
   * @return The bytes for modelHash.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getModelHashBytes() {
    java.lang.Object ref = modelHash_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      modelHash_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STATE_MACHINE_SYMBOL_ID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object stateMachineSymbolId_ = "";
  /**
   * <code>string state_machine_symbol_id = 2 [json_name = "stateMachineSymbolId"];</code>
   * @return The stateMachineSymbolId.
   */
  @java.lang.Override
  public java.lang.String getStateMachineSymbolId() {
    java.lang.Object ref = stateMachineSymbolId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      stateMachineSymbolId_ = s;
      return s;
    }
  }
  /**
   * <code>string state_machine_symbol_id = 2 [json_name = "stateMachineSymbolId"];</code>
   * @return The bytes for stateMachineSymbolId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStateMachineSymbolIdBytes() {
    java.lang.Object ref = stateMachineSymbolId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      stateMachineSymbolId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EVENTS_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList events_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <pre>
   * sequence of event names to process
   * </pre>
   *
   * <code>repeated string events = 3 [json_name = "events"];</code>
   * @return A list containing the events.
   */
  public com.google.protobuf.ProtocolStringList
      getEventsList() {
    return events_;
  }
  /**
   * <pre>
   * sequence of event names to process
   * </pre>
   *
   * <code>repeated string events = 3 [json_name = "events"];</code>
   * @return The count of events.
   */
  public int getEventsCount() {
    return events_.size();
  }
  /**
   * <pre>
   * sequence of event names to process
   * </pre>
   *
   * <code>repeated string events = 3 [json_name = "events"];</code>
   * @param index The index of the element to return.
   * @return The events at the given index.
   */
  public java.lang.String getEvents(int index) {
    return events_.get(index);
  }
  /**
   * <pre>
   * sequence of event names to process
   * </pre>
   *
   * <code>repeated string events = 3 [json_name = "events"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the events at the given index.
   */
  public com.google.protobuf.ByteString
      getEventsBytes(int index) {
    return events_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(modelHash_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, modelHash_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(stateMachineSymbolId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, stateMachineSymbolId_);
    }
    for (int i = 0; i < events_.size(); i++) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, events_.getRaw(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(modelHash_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, modelHash_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(stateMachineSymbolId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, stateMachineSymbolId_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < events_.size(); i++) {
        dataSize += computeStringSizeNoTag(events_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getEventsList().size();
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.opensysml.proto.ExecuteStateRequest)) {
      return super.equals(obj);
    }
    io.opensysml.proto.ExecuteStateRequest other = (io.opensysml.proto.ExecuteStateRequest) obj;

    if (!getModelHash()
        .equals(other.getModelHash())) return false;
    if (!getStateMachineSymbolId()
        .equals(other.getStateMachineSymbolId())) return false;
    if (!getEventsList()
        .equals(other.getEventsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MODEL_HASH_FIELD_NUMBER;
    hash = (53 * hash) + getModelHash().hashCode();
    hash = (37 * hash) + STATE_MACHINE_SYMBOL_ID_FIELD_NUMBER;
    hash = (53 * hash) + getStateMachineSymbolId().hashCode();
    if (getEventsCount() > 0) {
      hash = (37 * hash) + EVENTS_FIELD_NUMBER;
      hash = (53 * hash) + getEventsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.opensysml.proto.ExecuteStateRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.opensysml.proto.ExecuteStateRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.opensysml.proto.ExecuteStateRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.opensysml.proto.ExecuteStateRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.opensysml.proto.ExecuteStateRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.opensysml.proto.ExecuteStateRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.opensysml.proto.ExecuteStateRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.opensysml.proto.ExecuteStateRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.opensysml.proto.ExecuteStateRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.opensysml.proto.ExecuteStateRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.opensysml.proto.ExecuteStateRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.opensysml.proto.ExecuteStateRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.opensysml.proto.ExecuteStateRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * ExecuteStateRequest requests state machine execution
   * </pre>
   *
   * Protobuf type {@code sysml.ExecuteStateRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:sysml.ExecuteStateRequest)
      io.opensysml.proto.ExecuteStateRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.opensysml.proto.Sysml.internal_static_sysml_ExecuteStateRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.opensysml.proto.Sysml.internal_static_sysml_ExecuteStateRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.opensysml.proto.ExecuteStateRequest.class, io.opensysml.proto.ExecuteStateRequest.Builder.class);
    }

    // Construct using io.opensysml.proto.ExecuteStateRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      modelHash_ = "";
      stateMachineSymbolId_ = "";
      events_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.opensysml.proto.Sysml.internal_static_sysml_ExecuteStateRequest_descriptor;
    }

    @java.lang.Override
    public io.opensysml.proto.ExecuteStateRequest getDefaultInstanceForType() {
      return io.opensysml.proto.ExecuteStateRequest.getDefaultInstance();
    }

    @java.lang.Override
    public io.opensysml.proto.ExecuteStateRequest build() {
      io.opensysml.proto.ExecuteStateRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.opensysml.proto.ExecuteStateRequest buildPartial() {
      io.opensysml.proto.ExecuteStateRequest result = new io.opensysml.proto.ExecuteStateRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.opensysml.proto.ExecuteStateRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.modelHash_ = modelHash_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.stateMachineSymbolId_ = stateMachineSymbolId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        events_.makeImmutable();
        result.events_ = events_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.opensysml.proto.ExecuteStateRequest) {
        return mergeFrom((io.opensysml.proto.ExecuteStateRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.opensysml.proto.ExecuteStateRequest other) {
      if (other == io.opensysml.proto.ExecuteStateRequest.getDefaultInstance()) return this;
      if (!other.getModelHash().isEmpty()) {
        modelHash_ = other.modelHash_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getStateMachineSymbolId().isEmpty()) {
        stateMachineSymbolId_ = other.stateMachineSymbolId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.events_.isEmpty()) {
        if (events_.isEmpty()) {
          events_ = other.events_;
          bitField0_ |= 0x00000004;
        } else {
          ensureEventsIsMutable();
          events_.addAll(other.events_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              modelHash_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              stateMachineSymbolId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureEventsIsMutable();
              events_.add(s);
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object modelHash_ = "";
    /**
     * <code>string model_hash = 1 [json_name = "modelHash"];</code>
     * @return The modelHash.
     */
    public java.lang.String getModelHash() {
      java.lang.Object ref = modelHash_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        modelHash_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string model_hash = 1 [json_name = "modelHash"];</code>
     * @return The bytes for modelHash.
     */
    public com.google.protobuf.ByteString
        getModelHashBytes() {
      java.lang.Object ref = modelHash_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        modelHash_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string model_hash = 1 [json_name = "modelHash"];</code>
     * @param value The modelHash to set.
     * @return This builder for chaining.
     */
    public Builder setModelHash(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      modelHash_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string model_hash = 1 [json_name = "modelHash"];</code>
     * @return This builder for chaining.
     */
    public Builder clearModelHash() {
      modelHash_ = getDefaultInstance().getModelHash();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string model_hash = 1 [json_name = "modelHash"];</code>
     * @param value The bytes for modelHash to set.
     * @return This builder for chaining.
     */
    public Builder setModelHashBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      modelHash_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object stateMachineSymbolId_ = "";
    /**
     * <code>string state_machine_symbol_id = 2 [json_name = "stateMachineSymbolId"];</code>
     * @return The stateMachineSymbolId.
     */
    public java.lang.String getStateMachineSymbolId() {
      java.lang.Object ref = stateMachineSymbolId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        stateMachineSymbolId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string state_machine_symbol_id = 2 [json_name = "stateMachineSymbolId"];</code>
     * @return The bytes for stateMachineSymbolId.
     */
    public com.google.protobuf.ByteString
        getStateMachineSymbolIdBytes() {
      java.lang.Object ref = stateMachineSymbolId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stateMachineSymbolId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string state_machine_symbol_id = 2 [json_name = "stateMachineSymbolId"];</code>
     * @param value The stateMachineSymbolId to set.
     * @return This builder for chaining.
     */
    public Builder setStateMachineSymbolId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      stateMachineSymbolId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string state_machine_symbol_id = 2 [json_name = "stateMachineSymbolId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearStateMachineSymbolId() {
      stateMachineSymbolId_ = getDefaultInstance().getStateMachineSymbolId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string state_machine_symbol_id = 2 [json_name = "stateMachineSymbolId"];</code>
     * @param value The bytes for stateMachineSymbolId to set.
     * @return This builder for chaining.
     */
    public Builder setStateMachineSymbolIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      stateMachineSymbolId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList events_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureEventsIsMutable() {
      if (!events_.isModifiable()) {
        events_ = new com.google.protobuf.LazyStringArrayList(events_);
      }
      bitField0_ |= 0x00000004;
    }
    /**
     * <pre>
     * sequence of event names to process
     * </pre>
     *
     * <code>repeated string events = 3 [json_name = "events"];</code>
     * @return A list containing the events.
     */
    public com.google.protobuf.ProtocolStringList
        getEventsList() {
      events_.makeImmutable();
      return events_;
    }
    /**
     * <pre>
     * sequence of event names to process
     * </pre>
     *
     * <code>repeated string events = 3 [json_name = "events"];</code>
     * @return The count of events.
     */
    public int getEventsCount() {
      return events_.size();
    }
    /**
     * <pre>
     * sequence of event names to process
     * </pre>
     *
     * <code>repeated string events = 3 [json_name = "events"];</code>
     * @param index The index of the element to return.
     * @return The events at the given index.
     */
    public java.lang.String getEvents(int index) {
      return events_.get(index);
    }
    /**
     * <pre>
     * sequence of event names to process
     * </pre>
     *
     * <code>repeated string events = 3 [json_name = "events"];</code>
     * @param index The index of the value to return.
     * @return The bytes of the events at the given index.
     */
    public com.google.protobuf.ByteString
        getEventsBytes(int index) {
      return events_.getByteString(index);
    }
    /**
     * <pre>
     * sequence of event names to process
     * </pre>
     *
     * <code>repeated string events = 3 [json_name = "events"];</code>
     * @param index The index to set the value at.
     * @param value The events to set.
     * @return This builder for chaining.
     */
    public Builder setEvents(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureEventsIsMutable();
      events_.set(index, value);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * sequence of event names to process
     * </pre>
     *
     * <code>repeated string events = 3 [json_name = "events"];</code>
     * @param value The events to add.
     * @return This builder for chaining.
     */
    public Builder addEvents(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureEventsIsMutable();
      events_.add(value);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * sequence of event names to process
     * </pre>
     *
     * <code>repeated string events = 3 [json_name = "events"];</code>
     * @param values The events to add.
     * @return This builder for chaining.
     */
    public Builder addAllEvents(
        java.lang.Iterable<java.lang.String> values) {
      ensureEventsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, events_);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * sequence of event names to process
     * </pre>
     *
     * <code>repeated string events = 3 [json_name = "events"];</code>
     * @return This builder for chaining.
     */
    public Builder clearEvents() {
      events_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000004);;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * sequence of event names to process
     * </pre>
     *
     * <code>repeated string events = 3 [json_name = "events"];</code>
     * @param value The bytes of the events to add.
     * @return This builder for chaining.
     */
    public Builder addEventsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureEventsIsMutable();
      events_.add(value);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:sysml.ExecuteStateRequest)
  }

  // @@protoc_insertion_point(class_scope:sysml.ExecuteStateRequest)
  private static final io.opensysml.proto.ExecuteStateRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.opensysml.proto.ExecuteStateRequest();
  }

  public static io.opensysml.proto.ExecuteStateRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ExecuteStateRequest>
      PARSER = new com.google.protobuf.AbstractParser<ExecuteStateRequest>() {
    @java.lang.Override
    public ExecuteStateRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ExecuteStateRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ExecuteStateRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.opensysml.proto.ExecuteStateRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

