// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sysml.proto
// Protobuf Java Version: 4.33.1

package io.opensysml.proto;

@com.google.protobuf.Generated
public interface QueryResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sysml.QueryResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .sysml.QueryResultElement elements = 1 [json_name = "elements"];</code>
   */
  java.util.List<io.opensysml.proto.QueryResultElement> 
      getElementsList();
  /**
   * <code>repeated .sysml.QueryResultElement elements = 1 [json_name = "elements"];</code>
   */
  io.opensysml.proto.QueryResultElement getElements(int index);
  /**
   * <code>repeated .sysml.QueryResultElement elements = 1 [json_name = "elements"];</code>
   */
  int getElementsCount();
  /**
   * <code>repeated .sysml.QueryResultElement elements = 1 [json_name = "elements"];</code>
   */
  java.util.List<? extends io.opensysml.proto.QueryResultElementOrBuilder> 
      getElementsOrBuilderList();
  /**
   * <code>repeated .sysml.QueryResultElement elements = 1 [json_name = "elements"];</code>
   */
  io.opensysml.proto.QueryResultElementOrBuilder getElementsOrBuilder(
      int index);
}
