// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sysml.proto
// Protobuf Java Version: 4.33.1

package io.opensysml.proto;

@com.google.protobuf.Generated
public interface RunDocumentQueryResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sysml.RunDocumentQueryResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .sysml.DocumentQueryColumn columns = 1 [json_name = "columns"];</code>
   */
  java.util.List<io.opensysml.proto.DocumentQueryColumn> 
      getColumnsList();
  /**
   * <code>repeated .sysml.DocumentQueryColumn columns = 1 [json_name = "columns"];</code>
   */
  io.opensysml.proto.DocumentQueryColumn getColumns(int index);
  /**
   * <code>repeated .sysml.DocumentQueryColumn columns = 1 [json_name = "columns"];</code>
   */
  int getColumnsCount();
  /**
   * <code>repeated .sysml.DocumentQueryColumn columns = 1 [json_name = "columns"];</code>
   */
  java.util.List<? extends io.opensysml.proto.DocumentQueryColumnOrBuilder> 
      getColumnsOrBuilderList();
  /**
   * <code>repeated .sysml.DocumentQueryColumn columns = 1 [json_name = "columns"];</code>
   */
  io.opensysml.proto.DocumentQueryColumnOrBuilder getColumnsOrBuilder(
      int index);

  /**
   * <code>repeated .sysml.DocumentQueryRow rows = 2 [json_name = "rows"];</code>
   */
  java.util.List<io.opensysml.proto.DocumentQueryRow> 
      getRowsList();
  /**
   * <code>repeated .sysml.DocumentQueryRow rows = 2 [json_name = "rows"];</code>
   */
  io.opensysml.proto.DocumentQueryRow getRows(int index);
  /**
   * <code>repeated .sysml.DocumentQueryRow rows = 2 [json_name = "rows"];</code>
   */
  int getRowsCount();
  /**
   * <code>repeated .sysml.DocumentQueryRow rows = 2 [json_name = "rows"];</code>
   */
  java.util.List<? extends io.opensysml.proto.DocumentQueryRowOrBuilder> 
      getRowsOrBuilderList();
  /**
   * <code>repeated .sysml.DocumentQueryRow rows = 2 [json_name = "rows"];</code>
   */
  io.opensysml.proto.DocumentQueryRowOrBuilder getRowsOrBuilder(
      int index);
}
