// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sysml.proto
// Protobuf Java Version: 4.33.1

package io.opensysml.proto;

@com.google.protobuf.Generated
public interface SymbolResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sysml.SymbolResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.sysml.SymbolInfo symbol = 1 [json_name = "symbol"];</code>
   * @return Whether the symbol field is set.
   */
  boolean hasSymbol();
  /**
   * <code>.sysml.SymbolInfo symbol = 1 [json_name = "symbol"];</code>
   * @return The symbol.
   */
  io.opensysml.proto.SymbolInfo getSymbol();
  /**
   * <code>.sysml.SymbolInfo symbol = 1 [json_name = "symbol"];</code>
   */
  io.opensysml.proto.SymbolInfoOrBuilder getSymbolOrBuilder();

  /**
   * <code>string error = 2 [json_name = "error"];</code>
   * @return The error.
   */
  java.lang.String getError();
  /**
   * <code>string error = 2 [json_name = "error"];</code>
   * @return The bytes for error.
   */
  com.google.protobuf.ByteString
      getErrorBytes();
}
