// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sysml.proto
// Protobuf Java Version: 4.33.1

package io.opensysml.proto;

@com.google.protobuf.Generated
public interface ValueSequenceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sysml.ValueSequence)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .sysml.Value elements = 1 [json_name = "elements"];</code>
   */
  java.util.List<io.opensysml.proto.Value> 
      getElementsList();
  /**
   * <code>repeated .sysml.Value elements = 1 [json_name = "elements"];</code>
   */
  io.opensysml.proto.Value getElements(int index);
  /**
   * <code>repeated .sysml.Value elements = 1 [json_name = "elements"];</code>
   */
  int getElementsCount();
  /**
   * <code>repeated .sysml.Value elements = 1 [json_name = "elements"];</code>
   */
  java.util.List<? extends io.opensysml.proto.ValueOrBuilder> 
      getElementsOrBuilderList();
  /**
   * <code>repeated .sysml.Value elements = 1 [json_name = "elements"];</code>
   */
  io.opensysml.proto.ValueOrBuilder getElementsOrBuilder(
      int index);
}
