// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sysml.proto
// Protobuf Java Version: 4.33.1

package io.opensysml.proto;

/**
 * <pre>
 * VerifySatisfactionRequest asks whether the satisfaction assertions a model
 * states hold, as %satisfy does. Each is evaluated against an object of its
 * subject, built for the call.
 * </pre>
 *
 * Protobuf type {@code sysml.VerifySatisfactionRequest}
 */
@com.google.protobuf.Generated
public final class VerifySatisfactionRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:sysml.VerifySatisfactionRequest)
    VerifySatisfactionRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 1,
      /* suffix= */ "",
      "VerifySatisfactionRequest");
  }
  // Use VerifySatisfactionRequest.newBuilder() to construct.
  private VerifySatisfactionRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private VerifySatisfactionRequest() {
    modelHash_ = "";
    symbolId_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.opensysml.proto.Sysml.internal_static_sysml_VerifySatisfactionRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.opensysml.proto.Sysml.internal_static_sysml_VerifySatisfactionRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.opensysml.proto.VerifySatisfactionRequest.class, io.opensysml.proto.VerifySatisfactionRequest.Builder.class);
  }

  public static final int MODEL_HASH_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object modelHash_ = "";
  /**
   * <code>string model_hash = 1 [json_name = "modelHash"];</code>
   * @return The modelHash.
   */
  @java.lang.Override
  public java.lang.String getModelHash() {
    java.lang.Object ref = modelHash_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      modelHash_ = s;
      return s;
    }
  }
  /**
   * <code>string model_hash = 1 [json_name = "modelHash"];</code>
   * @return The bytes for modelHash.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getModelHashBytes() {
    java.lang.Object ref = modelHash_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      modelHash_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SYMBOL_ID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object symbolId_ = "";
  /**
   * <pre>
   * Optional FQN limiting evaluation: the assertions stated within that
   * element, or that element itself when it is a named satisfy assertion. Empty
   * evaluates every assertion the model states.
   * </pre>
   *
   * <code>string symbol_id = 2 [json_name = "symbolId"];</code>
   * @return The symbolId.
   */
  @java.lang.Override
  public java.lang.String getSymbolId() {
    java.lang.Object ref = symbolId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      symbolId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Optional FQN limiting evaluation: the assertions stated within that
   * element, or that element itself when it is a named satisfy assertion. Empty
   * evaluates every assertion the model states.
   * </pre>
   *
   * <code>string symbol_id = 2 [json_name = "symbolId"];</code>
   * @return The bytes for symbolId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSymbolIdBytes() {
    java.lang.Object ref = symbolId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      symbolId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(modelHash_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, modelHash_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(symbolId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, symbolId_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(modelHash_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, modelHash_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(symbolId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, symbolId_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.opensysml.proto.VerifySatisfactionRequest)) {
      return super.equals(obj);
    }
    io.opensysml.proto.VerifySatisfactionRequest other = (io.opensysml.proto.VerifySatisfactionRequest) obj;

    if (!getModelHash()
        .equals(other.getModelHash())) return false;
    if (!getSymbolId()
        .equals(other.getSymbolId())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MODEL_HASH_FIELD_NUMBER;
    hash = (53 * hash) + getModelHash().hashCode();
    hash = (37 * hash) + SYMBOL_ID_FIELD_NUMBER;
    hash = (53 * hash) + getSymbolId().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.opensysml.proto.VerifySatisfactionRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.opensysml.proto.VerifySatisfactionRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.opensysml.proto.VerifySatisfactionRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.opensysml.proto.VerifySatisfactionRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.opensysml.proto.VerifySatisfactionRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.opensysml.proto.VerifySatisfactionRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.opensysml.proto.VerifySatisfactionRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.opensysml.proto.VerifySatisfactionRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.opensysml.proto.VerifySatisfactionRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.opensysml.proto.VerifySatisfactionRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.opensysml.proto.VerifySatisfactionRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.opensysml.proto.VerifySatisfactionRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.opensysml.proto.VerifySatisfactionRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * VerifySatisfactionRequest asks whether the satisfaction assertions a model
   * states hold, as %satisfy does. Each is evaluated against an object of its
   * subject, built for the call.
   * </pre>
   *
   * Protobuf type {@code sysml.VerifySatisfactionRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:sysml.VerifySatisfactionRequest)
      io.opensysml.proto.VerifySatisfactionRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.opensysml.proto.Sysml.internal_static_sysml_VerifySatisfactionRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.opensysml.proto.Sysml.internal_static_sysml_VerifySatisfactionRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.opensysml.proto.VerifySatisfactionRequest.class, io.opensysml.proto.VerifySatisfactionRequest.Builder.class);
    }

    // Construct using io.opensysml.proto.VerifySatisfactionRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      modelHash_ = "";
      symbolId_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.opensysml.proto.Sysml.internal_static_sysml_VerifySatisfactionRequest_descriptor;
    }

    @java.lang.Override
    public io.opensysml.proto.VerifySatisfactionRequest getDefaultInstanceForType() {
      return io.opensysml.proto.VerifySatisfactionRequest.getDefaultInstance();
    }

    @java.lang.Override
    public io.opensysml.proto.VerifySatisfactionRequest build() {
      io.opensysml.proto.VerifySatisfactionRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.opensysml.proto.VerifySatisfactionRequest buildPartial() {
      io.opensysml.proto.VerifySatisfactionRequest result = new io.opensysml.proto.VerifySatisfactionRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.opensysml.proto.VerifySatisfactionRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.modelHash_ = modelHash_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.symbolId_ = symbolId_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.opensysml.proto.VerifySatisfactionRequest) {
        return mergeFrom((io.opensysml.proto.VerifySatisfactionRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.opensysml.proto.VerifySatisfactionRequest other) {
      if (other == io.opensysml.proto.VerifySatisfactionRequest.getDefaultInstance()) return this;
      if (!other.getModelHash().isEmpty()) {
        modelHash_ = other.modelHash_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getSymbolId().isEmpty()) {
        symbolId_ = other.symbolId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              modelHash_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              symbolId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object modelHash_ = "";
    /**
     * <code>string model_hash = 1 [json_name = "modelHash"];</code>
     * @return The modelHash.
     */
    public java.lang.String getModelHash() {
      java.lang.Object ref = modelHash_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        modelHash_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string model_hash = 1 [json_name = "modelHash"];</code>
     * @return The bytes for modelHash.
     */
    public com.google.protobuf.ByteString
        getModelHashBytes() {
      java.lang.Object ref = modelHash_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        modelHash_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string model_hash = 1 [json_name = "modelHash"];</code>
     * @param value The modelHash to set.
     * @return This builder for chaining.
     */
    public Builder setModelHash(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      modelHash_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string model_hash = 1 [json_name = "modelHash"];</code>
     * @return This builder for chaining.
     */
    public Builder clearModelHash() {
      modelHash_ = getDefaultInstance().getModelHash();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string model_hash = 1 [json_name = "modelHash"];</code>
     * @param value The bytes for modelHash to set.
     * @return This builder for chaining.
     */
    public Builder setModelHashBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      modelHash_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object symbolId_ = "";
    /**
     * <pre>
     * Optional FQN limiting evaluation: the assertions stated within that
     * element, or that element itself when it is a named satisfy assertion. Empty
     * evaluates every assertion the model states.
     * </pre>
     *
     * <code>string symbol_id = 2 [json_name = "symbolId"];</code>
     * @return The symbolId.
     */
    public java.lang.String getSymbolId() {
      java.lang.Object ref = symbolId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        symbolId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Optional FQN limiting evaluation: the assertions stated within that
     * element, or that element itself when it is a named satisfy assertion. Empty
     * evaluates every assertion the model states.
     * </pre>
     *
     * <code>string symbol_id = 2 [json_name = "symbolId"];</code>
     * @return The bytes for symbolId.
     */
    public com.google.protobuf.ByteString
        getSymbolIdBytes() {
      java.lang.Object ref = symbolId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        symbolId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Optional FQN limiting evaluation: the assertions stated within that
     * element, or that element itself when it is a named satisfy assertion. Empty
     * evaluates every assertion the model states.
     * </pre>
     *
     * <code>string symbol_id = 2 [json_name = "symbolId"];</code>
     * @param value The symbolId to set.
     * @return This builder for chaining.
     */
    public Builder setSymbolId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      symbolId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional FQN limiting evaluation: the assertions stated within that
     * element, or that element itself when it is a named satisfy assertion. Empty
     * evaluates every assertion the model states.
     * </pre>
     *
     * <code>string symbol_id = 2 [json_name = "symbolId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSymbolId() {
      symbolId_ = getDefaultInstance().getSymbolId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional FQN limiting evaluation: the assertions stated within that
     * element, or that element itself when it is a named satisfy assertion. Empty
     * evaluates every assertion the model states.
     * </pre>
     *
     * <code>string symbol_id = 2 [json_name = "symbolId"];</code>
     * @param value The bytes for symbolId to set.
     * @return This builder for chaining.
     */
    public Builder setSymbolIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      symbolId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:sysml.VerifySatisfactionRequest)
  }

  // @@protoc_insertion_point(class_scope:sysml.VerifySatisfactionRequest)
  private static final io.opensysml.proto.VerifySatisfactionRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.opensysml.proto.VerifySatisfactionRequest();
  }

  public static io.opensysml.proto.VerifySatisfactionRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<VerifySatisfactionRequest>
      PARSER = new com.google.protobuf.AbstractParser<VerifySatisfactionRequest>() {
    @java.lang.Override
    public VerifySatisfactionRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<VerifySatisfactionRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<VerifySatisfactionRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.opensysml.proto.VerifySatisfactionRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

