// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sysml.proto
// Protobuf Java Version: 4.33.1

package io.opensysml.proto;

@com.google.protobuf.Generated
public interface VerifyRequirementResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sysml.VerifyRequirementResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.sysml.Verdict verdict = 1 [json_name = "verdict"];</code>
   * @return Whether the verdict field is set.
   */
  boolean hasVerdict();
  /**
   * <code>.sysml.Verdict verdict = 1 [json_name = "verdict"];</code>
   * @return The verdict.
   */
  io.opensysml.proto.Verdict getVerdict();
  /**
   * <code>.sysml.Verdict verdict = 1 [json_name = "verdict"];</code>
   */
  io.opensysml.proto.VerdictOrBuilder getVerdictOrBuilder();

  /**
   * <code>repeated .sysml.Instance instances = 2 [json_name = "instances"];</code>
   */
  java.util.List<io.opensysml.proto.Instance> 
      getInstancesList();
  /**
   * <code>repeated .sysml.Instance instances = 2 [json_name = "instances"];</code>
   */
  io.opensysml.proto.Instance getInstances(int index);
  /**
   * <code>repeated .sysml.Instance instances = 2 [json_name = "instances"];</code>
   */
  int getInstancesCount();
  /**
   * <code>repeated .sysml.Instance instances = 2 [json_name = "instances"];</code>
   */
  java.util.List<? extends io.opensysml.proto.InstanceOrBuilder> 
      getInstancesOrBuilderList();
  /**
   * <code>repeated .sysml.Instance instances = 2 [json_name = "instances"];</code>
   */
  io.opensysml.proto.InstanceOrBuilder getInstancesOrBuilder(
      int index);

  /**
   * <code>string error = 3 [json_name = "error"];</code>
   * @return The error.
   */
  java.lang.String getError();
  /**
   * <code>string error = 3 [json_name = "error"];</code>
   * @return The bytes for error.
   */
  com.google.protobuf.ByteString
      getErrorBytes();

  /**
   * <code>repeated .sysml.Diagnostic diagnostics = 4 [json_name = "diagnostics"];</code>
   */
  java.util.List<io.opensysml.proto.Diagnostic> 
      getDiagnosticsList();
  /**
   * <code>repeated .sysml.Diagnostic diagnostics = 4 [json_name = "diagnostics"];</code>
   */
  io.opensysml.proto.Diagnostic getDiagnostics(int index);
  /**
   * <code>repeated .sysml.Diagnostic diagnostics = 4 [json_name = "diagnostics"];</code>
   */
  int getDiagnosticsCount();
  /**
   * <code>repeated .sysml.Diagnostic diagnostics = 4 [json_name = "diagnostics"];</code>
   */
  java.util.List<? extends io.opensysml.proto.DiagnosticOrBuilder> 
      getDiagnosticsOrBuilderList();
  /**
   * <code>repeated .sysml.Diagnostic diagnostics = 4 [json_name = "diagnostics"];</code>
   */
  io.opensysml.proto.DiagnosticOrBuilder getDiagnosticsOrBuilder(
      int index);
}
