# Generated by opensysml.generate. Do not edit.
"""Typed views over SysML definitions, generated from a parsed model."""

from __future__ import annotations

from opensysml import typed as _t

SYSML_GENERATOR_VERSION = "3"
"""Emission schema this module was generated with."""

SYSML_MODEL_HASH = "sha256:6bf5864bb94414fa79e77c1c2f7b0d6c0dcdf1174a6a20adeecc7d0b6754146b"
"""Hash of the model source this module was generated from."""


class Engine(_t.TypedObject):
    """partDef Demo::Engine."""

    sysml_id = "Demo::Engine"

    @property
    def power(self) -> float:
        """attributeUsage Demo::Engine::power."""
        return _t.feature_value(self, "power", _t.as_float)


class Vehicle(_t.TypedObject):
    """partDef Demo::Vehicle."""

    sysml_id = "Demo::Vehicle"

    @property
    def engine(self) -> Engine:
        """partUsage Demo::Vehicle::engine."""
        return _t.feature_value(self, "engine", _t.as_typed(Engine))

    @property
    def mass(self) -> float:
        """attributeUsage Demo::Vehicle::mass."""
        return _t.feature_value(self, "mass", _t.as_float)
