# Generated by pysysml.generate. Do not edit.
"""Typed views over SysML definitions, generated from a parsed model."""

from __future__ import annotations

from pysysml import typed as _t

SYSML_GENERATOR_VERSION = "1"
"""Emission schema this module was generated with."""

SYSML_MODEL_HASH = "sha256:fdfb382a055a458ee6d161e64d120ddf0f4711b3d38a7279e0fc3536ff194fdf"
"""Hash of the model source this module was generated from."""


class Engine(_t.TypedObject):
    """partDef Demo::Engine."""

    sysml_id = "Demo::Engine"

    @property
    def power(self) -> float:
        """attributeUsage Demo::Engine::power."""
        return _t.slot(self, "power", _t.as_float)


class Vehicle(_t.TypedObject):
    """partDef Demo::Vehicle."""

    sysml_id = "Demo::Vehicle"

    @property
    def engine(self) -> Engine:
        """partUsage Demo::Vehicle::engine."""
        return _t.slot(self, "engine", _t.as_typed(Engine))

    @property
    def mass(self) -> float:
        """attributeUsage Demo::Vehicle::mass."""
        return _t.slot(self, "mass", _t.as_float)
